### ISSUE TITLE
[TODO] 使用发行版携带的 GeoSite, GeoIP

### ISSUE THREAD

**Issue by kslr** [v2fly/fhs-install-v2ray#112]

**Comment by IceCodeNew** [comment]
这样做的原因是什么呢？

**Comment by kslr** [comment]
> 这样做的原因是什么呢？

未来的分发路径优化

**Comment by IceCodeNew** [comment]
https://github.com/v2fly/fhs-install-v2ray/blob/4706d8e46c0d4e4ff7bd781a3b9d1fa104315367/install-release.sh#L330-L347

目前 `install-release.sh` 脚本的逻辑就是从发行版里获得 `geosite.dat` 和 `geoip.dat` 文件的。
而另一个脚本在升级和安装 v2ray 时都不会用上，只是给有需要的用户主动升级上述文件时才手动调用的。

**Comment by IceCodeNew** [comment]
> > 这样做的原因是什么呢？
> 
> 未来的分发路径优化

其实我反而觉得让发行版文件越小越好。尤其是 `.dat` 文件对服务器配置来说很多时候还都是不必要的，因此在单独的逻辑里下载这些文件在我看来反而是更好的做法。
不过我也很想详细了解你这里说的分发路径优化具体指什么。

**Comment by kslr** [comment]
Dat 是运行必须的文件。

为了解决域名封锁，可以集中处理一个。

IceCodeNew <notifications@github.com> 于 2020年9月19日周六 下午6:02写道：
