### ISSUE TITLE
申请对 v2fly/fhs-install-v2ray 仓库的更高权限。

### ISSUE THREAD

**Issue by IceCodeNew** [v2fly/fhs-install-v2ray#115]
就是让我也可以去修改 repo settings 的程度。
打算集成一个 GitHub Actions，但现在我是看不到 settings 页的。也就是说必要的时候我好像无法给 repo 添加 actions 所需要的 secrets。

**Comment by kslr** [comment]
已经设置为维护者

**Comment by IceCodeNew** [comment]
好像还是没有改善 @kslr 

我希望能够访问的有：
https://github.com/v2fly/fhs-install-v2ray/settings/security_analysis
https://github.com/v2fly/fhs-install-v2ray/settings/secrets

然而我能看到的范围只有：
![image](https://user-images.githubusercontent.com/32576256/93671545-728cd900-fad6-11ea-8ec4-0489222f53aa.png)

**Comment by kslr** [comment]
非常抱歉，考虑到加入不足2个月，我不能给你管理员权限。
你需要什么写什么信息呢

**Comment by IceCodeNew** [comment]
我打算开启 Dependabot security updates，这样可以自动更新 workflow 上的 lint 版本。

**Comment by kslr** [comment]
> 我打算开启 Dependabot security updates，这样可以自动更新 workflow 上的 lint 版本。

security 里都打开了
