### ISSUE TITLE
使用VLESS协议通过systemctl start v2ray 无法启动, 但是可以使用配置文件启动(一旦断开ssh,v2ray也随之关闭)

### ISSUE THREAD

**Issue by WordsWorthLess** [v2fly/fhs-install-v2ray#121]
**服务器配置的方案是:**
`v2ray + tls + ws (nginx反代) + web `
**问题所在**
 经测试, 网页可以正常打开 , 使用vmess协议 , 可以正常通过systemctl start v2ray启动 , 
但是如果改为vless协议 , 那么 服务启动不成果 ,只能通过用 **v2ray -config /usr/local/etc/v2ray/config.json**来启动
而且一旦退出ssh, v2ray服务就会自动关闭

**service v2ray status输出如下:**

> ● v2ray.service - V2Ray Service
>   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
> Drop-In: /etc/systemd/system/v2ray.service.d
>           └─10-donot_touch_single_conf.conf
>   Active: failed (Result: exit-code) since Sun 2020-09-20 06:42:36 CEST; 10min ago
>     Docs: https://www.v2fly.org/
>  Process: 170 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json (code=exited, status=23)
>  Main PID: 170 (code=exited, status=23)

**journalctl --boot -u v2ray 输出如下:**
>Sep 20 05:37:10 srv11326 v2ray[1050]: V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
>Sep 20 05:37:10 srv11326 v2ray[1050]: A unified platform for anti-censorship.
>Sep 20 05:37:11 srv11326 systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
>Sep 20 05:37:11 srv11326 systemd[1]: v2ray.service: Unit entered failed state.
>Sep 20 05:37:11 srv11326 systemd[1]: v2ray.service: Failed with result 'exit-code'.
>Sep 20 05:42:08 srv11326 systemd[1]: Stopped V2Ray Service.
>Sep 20 05:42:08 srv11326 systemd[1]: Started V2Ray Service.
>Sep 20 05:42:08 srv11326 v2ray[1072]: V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
>Sep 20 05:42:08 srv11326 v2ray[1072]: A unified platform for anti-censorship.
>Sep 20 05:42:08 srv11326 systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
>Sep 20 05:42:08 srv11326 systemd[1]: v2ray.service: Unit entered failed state.
>Sep 20 05:42:08 srv11326 systemd[1]: v2ray.service: Failed with result 'exit-code'.
>Sep 20 05:42:20 srv11326 systemd[1]: Stopped V2Ray Service.
>Sep 20 05:42:20 srv11326 systemd[1]: Started V2Ray Service.
>Sep 20 05:42:20 srv11326 v2ray[1096]: V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
>Sep 20 05:42:20 srv11326 v2ray[1096]: A unified platform for anti-censorship.
>Sep 20 05:42:21 srv11326 v2ray[1096]: 2020/09/20 05:42:21 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
>Sep 20 05:42:21 srv11326 v2ray[1096]: v2ctl> Read config:  /usr/local/etc/v2ray/config.json
>Sep 20 05:42:21 srv11326 v2ray[1096]: main: failed to create server > v2ray.com/core/app/log: failed to initialize access logger > open /var/log/v2ray/access_vless.log: permission denied
>Sep 20 05:42:21 srv11326 systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
>Sep 20 05:42:21 srv11326 systemd[1]: v2ray.service: Unit entered failed state.
>Sep 20 05:42:21 srv11326 systemd[1]: v2ray.service: Failed with result 'exit-code'.
>Sep 20 05:45:45 srv11326 systemd[1]: Stopped V2Ray Service.
>Sep 20 05:45:45 srv11326 systemd[1]: Started V2Ray Service.
>Sep 20 05:45:45 srv11326 v2ray[1147]: V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
>Sep 20 05:45:45 srv11326 v2ray[1147]: A unified platform for anti-censorship.
>Sep 20 05:45:45 srv11326 v2ray[1147]: 2020/09/20 05:45:45 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
>Sep 20 05:45:45 srv11326 v2ray[1147]: v2ctl> Read config:  /usr/local/etc/v2ray/config.json
>Sep 20 05:45:45 srv11326 systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
>Sep 20 05:45:45 srv11326 systemd[1]: v2ray.service: Unit entered failed state.
>Sep 20 05:45:45 srv11326 systemd[1]: v2ray.service: Failed with result 'exit-code'.`

**vless配置文件:**

>{
>    "log": {
>        "loglevel": "warning",
>        "access": "/var/log/v2ray/access_vless.log",
>        "error": "/var/log/v2ray/error_vless.log"
>    },
>    "inbounds": [
>        {
>            "port": 12345,
>            "protocol": "VLESS",
>            "settings": {
>                "clients": [
>                    {
>                        "id": "UUID", // 填写你的 UUID
>                        "level": 0
>                    }
>               ],
>                "decryption": "none"
>            },
>            "streamSettings": {
>                "network": "ws",
>                "wsSettings": {
>                                "path": "/PATH"
>                }
>            }
>        }
>        ],
>   "outbounds":[
>        {
>            "protocol": "freedom",
>            "settings": {}
>        }
>    ]
>}

**error log 输出  如下:**
>2020/09/20 05:47:19 [Warning] [4005841939] v2ray.com/core/app/proxyman/inbound: connection ends >v2ray.com/core/proxy/vless/inbound: invalid request from clientIP:43070 > v2ray.com/core/proxy/vless/encoding: invalid request version
>2020/09/20 05:47:25 [Warning] [3098281814] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from clientIP:43194 > v2ray.com/core/proxy/vless/encoding: invalid request version
>2020/09/20 05:47:26 [Warning] [733914907] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from  clientIP:43212 > v2ray.com/core/proxy/vless/encoding: invalid request version
>2020/09/20 05:47:32 [Warning] [803053280] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from   clientIP:43336 > v2ray.com/core/proxy/vless/encoding: invalid request version
>2020/09/20 05:47:36 [Warning] [3497821748] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from  clientIP:43406 > v2ray.com/core/proxy/vless/encoding: invalid request version
>2020/09/20 05:47:39 [Warning] [1325712838] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from  clientIP:43456 > v2ray.com/core/proxy/vless/encoding: invalid request version
>2020/09/20 05:47:42 [Warning] [4158672352] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from  clientIP:43550 > v2ray.com/core/proxy/vless/encoding: invalid request version

**Comment by IceCodeNew** [comment]
你提了两个问题，其中关于 VLESS 协议无法使用的问题与本项目无关，你不必贴 v2ray 的 error log（并且你没有对这个 log 做适当的脱敏，客户端 IP 泄露了）
关于 systemd 无法启动 v2ray 服务的问题，你遇到的应该是权限问题：
`failed to create server > v2ray.com/core/app/log: failed to initialize access logger > open /var/log/v2ray/access_vless.log: permission denied`

`ls -alF /var/log/v2ray`，然后把结果发回来。

**Comment by WordsWorthLess** [comment]
> ls -alF /var/log/v2ray
果然是权限问题 ,chown -R nobody:nobody /var/log/v2ray/access_vless.log && chown -R nobody:nobody /var/log/v2ray/error_vless.log就能解决了,谢谢您
