### ISSUE TITLE
中国方向的文件加速讨论

### ISSUE THREAD

**Issue by kslr** [v2fly/fhs-install-v2ray#122]
https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
https://cdn.jsdelivr.net/gh/v2fly/fhs-install-v2ray@master/install-release.sh

```bash
➜  ~ curl -i https://v2fly.sh
HTTP/2 302 
date: Sun, 20 Sep 2020 20:05:05 GMT
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
location: https://cdn.jsdelivr.net/gh/v2fly/fhs-install-v2ray@master/install-release.sh
cf-request-id: 054eb7ced70000efa6de85e200000005
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5d5e28c48d5defa6-NRT
```
```bash
curl -Lso- v2fly.sh | bash
curl -Lso- v2fly.org/go.sh | bash
curl -Lso- v2fly.org/install.sh | bash
curl -Lso- v2fly.app/install.sh | bash
```

**Comment by kslr** [comment]
get.v2fly.sh

**Comment by IlO0OlI** [comment]
不要用jsdelivr，jsdelivr会对中国用户进行文件审核！
比如原v2ray的LICENSE文件：
`https://cdn.jsdelivr.net/gh/v2ray/v2ray-core@master/LICENSE`
jsdelivr给出的CDN地址为：
`https://cdn.jsdelivr.net/gh/v2ray/v2ray-core@master/LICENSE`
其内容如下：
`User v2ray is blocked in China. Please refer to https://github.com/v2ray/v2ray-core instead. See https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net for more information.`
v2fly仓库被屏蔽也是时间问题，更危险的是，jsdelivr可能会迫于压力修改脚本内容。

**Comment by LGTMXD** [comment]
https://git.io/v2fly.sh

**Comment by xiagw** [comment]
把sh文件用 `shc` 加密，然后置于cdn上，这样就不会被明文检查了。

SHC Shell Compiler » Linux Magazine
https://www.linux-magazine.com/Online/Features/SHC-Shell-Compiler
