### ISSUE TITLE
希望能显示下载进度条

### ISSUE THREAD

**Issue by kirin10000** [v2fly/fhs-install-v2ray#128]
Downloading V2Ray archive: $DOWNLOAD_LINK
的时候，有时因为网络环境不好，经常要下载很久，而不知道下载进度，会很焦急。我记得以前的脚本是有进度条显示的

**Comment by IceCodeNew** [comment]
这个建议我觉得值得考虑。事实上之前 @nicholascw 就做了两个直接到 master 分支的提交去掉了 curl 的 silent 参数。
https://github.com/v2fly/fhs-install-v2ray/commit/4554467c03dcef0a63314d85c9955aa8598cde90
https://github.com/v2fly/fhs-install-v2ray/commit/82f1734386e61c3c4042ee2f402009ae42eb4f3d

我不知道 curl 重新回归沉默的变化是什么时候引入的，甚至可能是我自己也说不定……但确实应该没有什么特殊的理由非得沉默 curl 不可。

**Comment by alx696** [comment]
体验确实不好，像是卡死了。在未被采纳前可以自行下载脚本后修改一下，去除小`s`即可。

https://github.com/v2fly/fhs-install-v2ray/pull/129/files#diff-74d43de9dd70a69c6a6717b91d6fd1f6
