### ISSUE TITLE
systemd failed to find service unit file.

### ISSUE THREAD

**Issue by GuRenYiBeiAiHuangLiang** [v2fly/fhs-install-v2ray#130]
Hi, I followed the readme to install v2ray on my azure instance (CentOS 8). But it seemed that systemd failed to load service unit file when executing any command, including ` systemctl enable` or ` systemctl start`. 
![image](https://user-images.githubusercontent.com/20686058/94108272-97d06d00-fe71-11ea-9495-2cd6955c694d.png)

And `systemctl list-unit-files --type=service` says that the status of v2ray is always `Bad` like the picture shows below.
![image](https://user-images.githubusercontent.com/20686058/94109221-40cb9780-fe73-11ea-8d5f-b705caa7e8ac.png)

**Comment by IceCodeNew** [comment]
没有告知你具体使用的脚本版本。
也没有 follow #63 的排查建议。

**Comment by kidlj** [comment]
Azure + CentOS 8 确实会遇到这个问题。把 SELinux 关掉就好了，重启机器就好了。

**Comment by GuRenYiBeiAiHuangLiang** [comment]
谢谢两位的回复，目前已经解决了。我拷贝了其他正常的service unit后将它改成v2ray需要用的形式就好了，不过我也没搞清楚是什么情况，因为他们的permission是一样的。下次配置新的节点时试试 @kidlj 的方法
