### ISSUE TITLE
对发布流程改善，利用 actions 执行脚本测试

### ISSUE THREAD

**Issue by kslr** [v2fly/fhs-install-v2ray#136]

**Comment by kslr** [comment]
2. 使用 release 控制

**Comment by IceCodeNew** [comment]
这块我已经在做了，不过暂时还需要完善，workflow file 我写得不太熟练。

**Comment by kslr** [comment]
run: |
 bash xxxx.sh 
就可以了，最后检查下文件都在不在该在的位置

**Comment by IceCodeNew** [comment]
https://github.com/v2fly/fhs-install-v2ray/commit/9bf2e117de926fd72101b252ee08fd952e4461a7

我按照你的建议做了，不过可能会有点问题，还要再观察观察。

**Comment by IceCodeNew** [comment]
Hmmmmmm, 本来纯用 ubuntu-latest 环境是可以测试了的。
但是我试着在 centos 的 docker 镜像里测试，这样可以尽可能确保脚本的兼容性，结果现在 GitHub Actions 就怎么都起不来了
@kslr 你能帮我看看 https://github.com/v2fly/fhs-install-v2ray/actions/runs/270811855 吗？

我是完全参考 https://github.com/actions/checkout/blob/1433f62caac9c18949f9a498f6f28c05388ea443/.github/workflows/test.yml#L138-L175 改的：
