### ISSUE TITLE
[Feature] 为脚本引入 `revision at yyyy-mm-dd-tag` 概念及更新功能

### ISSUE THREAD

**Issue by IceCodeNew** [v2fly/fhs-install-v2ray#138]
用了一次 https://github.com/slimm609/checksec.sh 项目，`checksec --update` 香爆了。
然后就想到现在本项目在排查用户使用问题时经常会有需要知道用户使用的脚本版本的需要，所以有意把前述项目的相关功能抄袭下来。

目前读过 https://github.com/slimm609/checksec.sh/blob/master/LICENSE.txt 觉得这样做应该是没有问题的，而且我一定会在抄袭完以后在 README 中为 slimm609/checksec.sh 项目加上应有的 credit。

如果有人觉得这样做不妥，或者有其他建议，欢迎在这条 Issue 下讨论。

**Comment by kslr** [comment]
默认使用最新版更符合需求

**Comment by IceCodeNew** [comment]
> 默认使用最新版更符合需求

当然，这里讨论的就是给脚本加上更新自己的功能。

**Comment by kslr** [comment]
没有必要做的太多

**Comment by IceCodeNew** [comment]
那就算了~
