### ISSUE TITLE
更新完bash install-dat-release.sh 报错

### ISSUE THREAD

**Issue by Eintler** [v2fly/fhs-install-v2ray#140]
root@localhost:~# curl -LROJ https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-dat-release.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2054  100  2054    0     0   7388      0 --:--:-- --:--:-- --:--:--  7362
root@localhost:~# bash install-dat-release.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   137  100   137    0     0    568      0 --:--:-- --:--:-- --:--:--   568
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147  100   147    0     0    576      0 --:--:-- --:--:-- --:--:--   576
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0    597      0 --:--:-- --:--:-- --:--:--   597
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   163  100   163    0     0    639      0 --:--:-- --:--:-- --:--:--   636
sha256sum: /tmp/tmp.yEw3kZ4ZZk/dlc.dat.sha256sum: no properly formatted SHA256 checksum lines found
error: Check failed! Please check your network or try again.

systemctl start  v2ray
Sep 24 22:31:20 localhost.localdomain systemd[1]: Started V2Ray Service.
Sep 24 22:31:20 localhost.localdomain v2ray[19314]: V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
Sep 24 22:31:20 localhost.localdomain v2ray[19314]: A unified platform for anti-censorship.
Sep 24 22:31:20 localhost.localdomain v2ray[19314]: main: failed to read config files: [/usr/local/etc/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config 
Sep 24 22:31:20 localhost.localdomain v2ray[19314]: v2ctl> Read config:  /usr/local/etc/v2ray/config.json
Sep 24 22:31:20 localhost.localdomain v2ray[19314]: v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > proto: mismatching end group mark
Sep 24 22:31:20 localhost.localdomain systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Sep 24 22:31:20 localhost.localdomain systemd[1]: v2ray.service: Failed with result 'exit-code'.

config

"routing": {
 86     "domainStrategy": "IPIfNonMatch",
 87     "rules":[
 88       {
 89         // Blocks access to private IPs. Remove this if you want to access your router.
 90         "type": "field",
 91         "ip": ["geoip:private"],
 92         "outboundTag": "direct"
 93       },
 94       {
 95         // Blocks major ads.
 96         "type": "field",
 97         "domain": ["geosite:category-ads"],
 98         "outboundTag": "blocked"
 99       }
100     ]
101   },
102 
103   // Dns settings for domain resolution.
104   "dns": {
105     // Static hosts, similar to hosts file.
106     "hosts": {
107       // Match v2ray.com to another domain on CloudFlare. This domain will be used when querying IPs for v2ray.com.
108       "domain:v2ray.com": "www.vicemc.net",
109 
110       // The following settings help to eliminate DNS poisoning in mainland China.
111       // It is safe to comment these out if this is not the case for you.
112       "domain:github.io": "pages.github.com",
113       "domain:wikipedia.org": "www.wikimedia.org",
114       "domain:shadowsocks.org": "electronicsrealm.com"
115     },
116     "servers": [
117       //DOHL请求不会经过Routing/Outbound等组件，直接对外请求，以降低耗时。一般适合在服务端使用。也可使用非标端口和路径。
118       "https+local://1.1.1.1/dns-query",
119       "1.1.1.1",
120       {
121         "address": "114.114.114.114",
122         "port": 53,
123         // List of domains that use this DNS first.
124         "domains": [
125           "geosite:cn"
126         ]
127       },
128       "8.8.8.8",
129       "localhost"
130     ]

2020/9/25 更新完出现的问题。

求教啊

**Comment by IceCodeNew** [comment]
Fixed by https://github.com/v2fly/fhs-install-v2ray/commit/9760e6fe1b175d814793cee4c2913b73a6d0e2bf
