### ISSUE TITLE
按照Migrate from the old script 修改后，权限出错

### ISSUE THREAD

**Issue by Eintler** [v2fly/fhs-install-v2ray#145]
chown -R nobody:nobody /var/log/v2ray/
chown: invalid group: ‘nobody:nobody’

求解

**Comment by IceCodeNew** [comment]
wiki 上明明把两种情况都写的很清楚了，你执行 `id nobody` 看了输出吗？
如果输出里面告诉你这个用户属于 `nogroup` 组那就 `chown -R nobody:nogroup /var/log/v2ray/`
> groups=****(nogroup)

否则才是 `chown -R nobody:nobody /var/log/v2ray/`
> groups=****(nobody)

**Comment by Eintler** [comment]
root@localhost:/# chown -R nobody:nobody /var/log/v2ray/
root@localhost:/# systemctl status v2ray
● v2ray.service - V2Ray Service
Loaded: loaded (/etc/systemd/system/v2ray.service; disabled; vendor preset: enabled)
Drop-In: /etc/systemd/system/v2ray.service.d
└─10-donot_touch_single_conf.conf
Active: failed (Result: exit-code) since Sun 2020-09-27 04:17:03 EDT; 2s ago
Docs: https://www.v2fly.org/
Process: 543 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json (code=exited, status=255)
Main PID: 543 (code=exited, status=255)

Sep 27 04:17:03 localhost.localdomain systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
Sep 27 04:17:03 localhost.localdomain systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 27 04:17:03 localhost.localdomain systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Sep 27 04:17:03 localhost.localdomain systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Sep 27 04:17:03 localhost.localdomain systemd[1]: Stopped V2Ray Service.
Sep 27 04:17:03 localhost.localdomain systemd[1]: v2ray.service: Start request repeated too quickly.
Sep 27 04:17:03 localhost.localdomain systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 27 04:17:03 localhost.localdomain systemd[1]: Failed to start V2Ray Service.

**Comment by IceCodeNew** [comment]
我已经说过了，你应该仔细看过 `id nobody` 的输出，在
`chown -R nobody:nogroup /var/log/v2ray/`
`chown -R nobody:nobody /var/log/v2ray/`
两个命令中选择适合你环境的来执行。

如果你实在理解不了这个意思，那你也应该想到一条命令走不通就换另一个命令也执行试试吧？
你完全不看别人的建议，光是把自己看到的错误信息 po 到 GitHub 上来又有什么意思呢？
你根本没有在接受别人的帮助。
