### ISSUE TITLE
以nobody启动报错

### ISSUE THREAD

**Issue by Eintler** [v2fly/fhs-install-v2ray#146]
root@localhost:/# systemctl status v2ray
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; disabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/v2ray.service.d
           └─10-donot_touch_single_conf.conf
   Active: failed (Result: exit-code) since Sun 2020-09-27 04:17:03 EDT; 2s ago
     Docs: https://www.v2fly.org/
  Process: 543 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json (code=exited, status=255)
 Main PID: 543 (code=exited, status=255)

Sep 27 04:17:03 localhost.localdomain systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
Sep 27 04:17:03 localhost.localdomain systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 27 04:17:03 localhost.localdomain systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Sep 27 04:17:03 localhost.localdomain systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Sep 27 04:17:03 localhost.localdomain systemd[1]: Stopped V2Ray Service.
Sep 27 04:17:03 localhost.localdomain systemd[1]: v2ray.service: Start request repeated too quickly.
Sep 27 04:17:03 localhost.localdomain systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 27 04:17:03 localhost.localdomain systemd[1]: Failed to start V2Ray Service.

**Comment by IceCodeNew** [comment]
如果 #145 的建议没有解决你的问题，你可以直接 reopen 那个 issue，而不是在这里 spam。
