### ISSUE TITLE
Nobody 用户如何改回Root 运行v2ray

### ISSUE THREAD

**Issue by ixxmu** [v2fly/fhs-install-v2ray#149]
Nobody 用户如何改回Root 运行v2ray，经常因为直接调用证书而运行失败

**Comment by IceCodeNew** [comment]
你已经试过这个教程了吗？
https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates-zh-Hans-CN

**Comment by dna1982** [comment]
just to answer your question.

`echo -e "[Service]\nUser=\nUser=root" > /etc/systemd/system/v2ray.service.d/09-custom_user_root.conf && systemctl daemon-reload && systemctl restart v2ray.service`

**Comment by wellsyue** [comment]
删除一行代码
/root/.acme.sh/acme.sh

![捕获](https://user-images.githubusercontent.com/32589117/146513332-3d727d0f-604a-4478-bbb1-00967e857cf8.JPG)
