### ISSUE TITLE
请问ipv6的vps如何安装？

### ISSUE THREAD

**Issue by csquya** [v2fly/fhs-install-v2ray#150]
我有一台ivp6的vps， 无法解析 raw.githubusercontent.com地址， 因此我设法从别的地方下载了 install-release.sh脚本上传到该vps， 可是还是提示无法连接到服务器， 于是我看了下， 发现 api.github.com 同样没有ipv6地址才造成的。

所以我该怎么安装， 在别的地方下载zip文件再上传安装？ 没有了自动安装的脚本，手动安装应该注意点啥， 比如生成服务，权限设置等等， 希望有经验的人不吝赐教， 谢谢！ 或者最简单的应该可以修改install-release.sh 跳过下载， 但是我是小白，不怎么懂。

另，顺便问下，这个v2fly 和 v2ray有啥区别，我被v2ray的老脚本引导到了这里，发现这儿的版本更新， 其他不知道有啥区别。

再另，raw.githubusercontent.com 这个地址即使 ipv4 有的地方也无法解析，它的指向（or 镜像？） github.map.fastly.net 却能解析。

**Comment by IceCodeNew** [comment]
纯 IPv6 的 VPS 确实暂时无法利用 GitHub 的服务。
你只需要在 https://github.com/v2fly/v2ray-core/releases 页面下载自己机器对应架构的压缩包再上传就好了（如果你对机器架构有疑问，可以 `uname -m` 确认
最后你执行脚本时需要传递 `--local` 参数来告诉脚本你把压缩包上传到哪儿了。

**Comment by csquya** [comment]
> 纯 IPv6 的 VPS 确实暂时无法利用 GitHub 的服务。
> 你只需要在 https://github.com/v2fly/v2ray-core/releases 页面下载自己机器对应架构的压缩包再上传就好了（如果你对机器架构有疑问，可以 `uname -m` 确认
> 最后你执行脚本时需要传递 `--local` 参数来告诉脚本你把压缩包上传到哪儿了。

谢谢， 你的意思还是和以前一样， 脚本可以用local参数， 比如 ./install-release.sh  --local /path/to/v2ray.zip， 简直太好了！！

**Comment by kirin10000** [comment]
使用dns64就行了，google cloudflare都有dns64服务
