### ISSUE TITLE
Debian 8 Jessie libarchive-tools

### ISSUE THREAD

**Issue by wsltshh** [v2fly/fhs-install-v2ray#156]
E: Unable to locate package libarchive-tools
error: Installation of libarchive-tools failed, please check your network.
8怎么安装，我搜搜也没明白，有可用的源吗？

**Comment by IceCodeNew** [comment]
Debian 8 已经到达了其生命的终点，本项目亦不会计划为其提供支持。

https://wiki.debian.org/LTS
![image](https://user-images.githubusercontent.com/32576256/95052328-523d5b00-0721-11eb-9eed-03db6c2e66ea.png)
