### ISSUE TITLE
无法更新v2ray-core到v4.31.0

### ISSUE THREAD

**Issue by onlyJinx** [v2fly/fhs-install-v2ray#158]
core已经更新到v4.31.0, 但是使用脚本更新时却提示无法检测到新版本, 当前版本为v4.30.0, 是我操作失误吗....

![image](https://user-images.githubusercontent.com/21324835/95645551-bdf14080-0af2-11eb-9195-d13219e48d3b.png)

![image](https://user-images.githubusercontent.com/21324835/95645529-8edacf00-0af2-11eb-8470-44bea6a64f93.png)

**Comment by kslr** [comment]
只是预览并没有发布

**Comment by onlyJinx** [comment]
明白了, 谢谢.
