### ISSUE TITLE
为什么我的v2ray+ws我法使用

### ISSUE THREAD

**Issue by peiqi01** [v2fly/fhs-install-v2ray#159]
`{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "dns": {},
  "stats": {},
  "inbounds": [
    {
      "port": 8090,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "efe318ab-3a00-4114-a8c7-18bd8bd9ab58",
            "alterId": 32
          }
        ]
      },
      "tag": "in-0",
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/qaz123"
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked"
      }
    ]
  },
  "policy": {},
  "reverse": {},
  "transport": {}
}`

这是我从网上一键生成的文件

`020/10/10 15:12:39 [Warning] [837094133] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://hk.9518.me:8090/qaz123):  > dial tcp 43.225.100.159:8090: connect: connection refused] > v2ray.com/core/common/retry: all retry attempts failed
`

**Comment by IceCodeNew** [comment]
本项目不负责解答 v2ray 使用上的疑问，请向上游提问。
还有提问前记得脱敏配置文件。
