### ISSUE TITLE
建议配置文件添加默认配置

### ISSUE THREAD

**Issue by xiebruce** [v2fly/fhs-install-v2ray#16]
配置文件分散开来后，确实方便点，不像以前那么冗长一直上下翻来翻去，但目前默认都是空的，不方便新手添加配置。

### 建议一：添加默认配置格式
把各个配置文件添加上默认配置，用户就可以直接在上面按原来的格式修改，这样不容易出错。需要高级用法再去查文档

### 建议二：v2ray考虑支持一下yaml
json格式很坑，注释也不方便，虽然现在支持注释，但标准json是不支持的，我们没法用json检测工具去检测有注释的json，因为那样肯定报错，但每次把注释删除再检测又很麻烦，而有时候又确实需要注释，而且就算不用注释，用yaml也没json那么坑，所以不知道v2ray有没有考虑过支持一下yaml。

**Comment by tzwjkl** [comment]
建议二貌似应该去v2ray-core项目里反映

**Comment by dctxmei** [comment]
針對「建議一」，或許可以參照該項目的方式：
https://github.com/rime/plum

**Comment by kslr** [comment]
https://github.com/v2fly/v2ray-examples
