### ISSUE TITLE
在ubuntu 16.04 lts上安装4.31.0有问题

### ISSUE THREAD

**Issue by UJX6N** [v2fly/fhs-install-v2ray#160]
脚本说依赖
libarchive13
libarchive-tools
并自动发起apt安装，但报
Depends: libarchive13 (= 3.2.1-2~ubuntu16.04.1) but 3.1.2-11ubuntu0.16.04.8 is to be installed
依赖包和v2ray都没有安装成功

看了下
libarchive (3.2.1-2~ubuntu16.04.1)
属于xenial-backports里的包，apt的时候需要加参数
-t xenial-backports
否则apt源还是找到xenial原版的3.1.2-11ubuntu0.16.04.8
安装脚本应该没为ubuntu 16.04考虑-t xenial-backports

手工运行
apt install -t xenial-backports libarchive13 libarchive-tools
之后，再安装4.31.0就成功了

**Comment by IceCodeNew** [comment]
你说的很对，16.04 是 4 年前的发行版了，我确实没有计划考虑它。
不过我还是要说一句，正常的 Ubuntu server 模板是应该要开启 backports 源的，这就是我为什么觉得我不需要特别为 xenial 考虑的原因。

对于其他同样因为不知道什么原因没有开启 backports 源的用户，你的经验很有用，感谢分享。

**Comment by felixqu** [comment]
打开backports 后成功了，谢谢
