### ISSUE TITLE
Install script may require manual intervention when console size is small

### ISSUE THREAD

**Issue by camellia256** [v2fly/fhs-install-v2ray#161]
## Problem
The script hangs on `systemd-analyze cat-config` output when console size is small and requires manual intervention to continue. By default, `systemd-analyze cat-config` automatically pipes output to a pager when output exceeds console size. This behavior should be disabled in a non-interactive script.
## Proposed fix
Change
https://github.com/v2fly/fhs-install-v2ray/blob/32d5d6e06051c3e1515d1d58c3f9504ba1fb18ef/install-release.sh#L35
to
```bash
systemd-analyze --no-pager cat-config "$@" 
```

**Comment by IceCodeNew** [comment]
Good catch, I'll fix this issue later.
