### ISSUE TITLE
v2ray状态异常

### ISSUE THREAD

**Issue by marklsl** [v2fly/fhs-install-v2ray#163]
使用service v2ray status时，出现下列提示
Oct 12 19:02:14 rave-nerds-1.localdomain systemd[1]: v2ray.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[root@rave-nerds-1 /]# systemctl start v2ray
[root@rave-nerds-1 /]# service v2ray status
Redirecting to /bin/systemctl status  v2ray.service
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/v2ray.service.d
           └─10-donot_touch_single_conf.conf
   Active: failed (Result: start-limit) since Wed 2010-10-13 07:15:32 EDT; 431ms ago
     Docs: https://www.v2fly.org/
  Process: 8524 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json (code=exited, status=255)
 Main PID: 8524 (code=exited, status=255)

**Comment by IceCodeNew** [comment]
1. 你用的指令太舊了
2. 參考 #63 排查錯誤，把結果發上來

**Comment by marklsl** [comment]
你好，以下是我的排查日志。您能看出问题出在哪里吗？

运行：journalctl --boot -u v2ray
` rave-nerds-1.localdomain systemd[1]: Started V2Ray Service.
rave-nerds-1.localdomain systemd[1]: Starting V2Ray Service...
 rave-nerds-1.localdomain v2ray[1111]: V2Ray 4.30.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
rave-nerds-1.localdomain v2ray[1111]: A unified platform for anti-censorship.
rave-nerds-1.localdomain v2ray[1111]: 2020/10/12 07:13:39 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
rave-nerds-1.localdomain v2ray[1111]: v2ctl> Read config:  /usr/local/etc/v2ray/config.json
rave-nerds-1.localdomain systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
rave-nerds-1.localdomain systemd[1]: Unit v2ray.service entered failed state.
rave-nerds-1.localdomain systemd[1]: v2ray.service failed.`

运行：V2RAY_LOCATION_ASSET=/usr/local/share/v2ray/ v2ray -test -confdir /usr/local/etc/v2ray/
`Configuration OK.`

运行：ls -alF --color=auto /usr/local/etc/v2ray
`total 12
drwxr-xr-x  2 root root 4096 Oct 13 06:39 ./
drwxr-xr-x. 3 root root 4096 Oct  9 08:30 ../
-rw-r--r--  1 root root 1601 Oct 13  2010 config.json`

运行：systemd-analyze cat-config /etc/systemd/system/v2ray.service
`Unknown operation 'cat-config'.`

运行：systemd-analyze verify /etc/systemd/system/v2ray.service
`Unknown lvalue 'AmbientCapabilities' in section 'Service'`

**Comment by DuckSoft** [comment]
盲猜 systemd 版本过于上古。

**Comment by IceCodeNew** [comment]
`运行：systemd-analyze cat-config /etc/systemd/system/v2ray.service
Unknown operation 'cat-config'.`

你没有在用最新版本的脚本，先遵照 README 上的建议，始终使用最新版本的脚本。

**Comment by marklsl** [comment]
是指`bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)`
       `bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-dat-release.sh)`？
我安装使用的就是这两个脚本。目前v2ray版本是4.31.0

**Comment by ghq200101** [comment]
后来怎么解决的呀，我也遇到Unknown operation 'cat-config'.的问题。
