### ISSUE TITLE
Using the SOCKS5 to install data failed

### ISSUE THREAD

**Issue by whg517** [v2fly/fhs-install-v2ray#167]
I installed the V2Ray agent on the client side, its ok, and when I configured the global agent(export https_proxy=192.168.1.2:1080) on another machine(centos 8), the script for the installation data could not run properly.

This was normal after I used [a tool](https://github.com/snail007/goproxy) to convert the SOCKS5 proxy to an HTTP/HTTPS proxy.

I don't understand why the installation of v2Ray script is ok, but the installation of data script is abnormal, I hope to fix it, thank you

```
[root@a7c8bc02168a ~]# export http_proxy=socks5://192.168.×.×:1080
[root@a7c8bc02168a ~]# export https_proxy=socks5://192.168.×.×:1080
[root@a7c8bc02168a ~]# 
[root@a7c8bc02168a ~]# curl http://httpbin.org/ip         
{
  "origin": "167.×.×.244"
}
[root@a7c8bc02168a ~]# bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-dat-release.sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2039  100  2039    0     0   3546      0 --:--:-- --:--:-- --:--:--  3539
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   137  100   137    0     0    189      0 --:--:-- --:--:-- --:--:--   189
100   635  100   635    0     0    603      0  0:00:01  0:00:01 --:--:--   603
100 5018k  100 5018k    0     0  1426k      0  0:00:03  0:00:03 --:--:-- 2600k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147  100   147    0     0    205      0 --:--:-- --:--:-- --:--:--   205
100   645  100   645    0     0    623      0  0:00:01  0:00:01 --:--:--  629k
curl: (7) Failed to receive SOCKS5 connect request ack.
error: Download failed! Please check your network or try again.
[root@a7c8bc02168a ~]# 
```

**Comment by IceCodeNew** [comment]
Just type `bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-dat-release.sh) -h` and you will see this script had already support that feature.

Pass your local proxy address to the script with `-x` option.

**Comment by IceCodeNew** [comment]
`curl: (7) Failed to receive SOCKS5 connect request ack.`
Just google this error message.
https://github.com/curl/curl/issues/365#issuecomment-297937544

IMO, this issue doesn't seem relevant to this project or the curl project.
Try to troubleshoot the socks server `goproxy` you are using locally first.

**Comment by DuckSoft** [comment]
socks5h

**Comment by whg517** [comment]
@DuckSoft Thansk a lot.
