### ISSUE TITLE
[wiki][VLESS]

### ISSUE THREAD

**Issue by kirin10000** [v2fly/fhs-install-v2ray#169]
https://github.com/v2fly/fhs-install-v2ray/wiki/To-use-the-VLESS-protocol-zh-Hans-CN
不是很明白，这里通篇都在讲证书和权限管理，和VLESS有什么关系？

**Comment by mixool** [comment]
> 注意：千万注意 fallbacks 所在入站本身必须是 TCP+TLS，这是分流至其它 WS 入站用的，被分流的入站则无需配置 TLS 了
  
因为vless一般都是443tls+fallbacks使用.需要配置证书路径,需要权限

光看不懂的话亲手配置一遍就知道了

**Comment by kirin10000** [comment]
> 
> 因为vless一般都是443tls+fallbacks使用.需要配置证书路径,需要权限

VLESS作为一个目标全场景的协议，我认为不应该与TLS绑定。
https://github.com/v2ray/v2ray-core/issues/2636
同样的TLS也不止用于VLESS，VMess+TCP+TLS，VMess+ws+TLS，都是常用的协议

> 
> 光看不懂的话亲手配置一遍就知道了

配置过很多了
