### ISSUE TITLE
对当前项目的一点建议

### ISSUE THREAD

**Issue by unknowndev233** [v2fly/fhs-install-v2ray#17]
1. 目前项目中 geoip.dat 和 geosite.dat 的放置位置并不够准确，因为 geoip.dat 和 geosize.dat 属于架构无关的文件，所以它们应该在 `/usr/loacl/share/v2ray` 下
[lib](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s06.html)
[share](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html)

2. 希望在 After= 增加 network-online.target
为什么要把这个扔掉的选项加回来？因为我发现这个选项对客户端与转发是有用处的
意在不会出现网络并没有准备好但是还是会启动 v2ray 导致一些可能的问题

**Comment by MuenYu** [comment]
想问一下如果存放到上述目录后，v2ray如何引用dat文件

目前根据脚本，dat文件会被下载到`/usr/local/lib/v2ray/`下，根据[V2ray配置指南](https://toutyrater.github.io/routing/sitedata.html)中v2ray只能识别程序目录下的dat的文件，如我有误解，还请指导！

谢谢！

**Comment by kslr** [comment]
> 想问一下如果存放到上述目录后，v2ray如何引用dat文件
> 
> 目前根据脚本，dat文件会被下载到`/usr/local/lib/v2ray/`下，根据[V2ray配置指南](https://toutyrater.github.io/routing/sitedata.html)中v2ray只能识别程序目录下的dat的文件，如我有误解，还请指导！
> 
> 谢谢！

通过指定环境变量路径

**Comment by MuenYu** [comment]
@kslr 感谢！

**Comment by unknowndev233** [comment]
> > 想问一下如果存放到上述目录后，v2ray如何引用dat文件
> > 目前根据脚本，dat文件会被下载到`/usr/local/lib/v2ray/`下，根据[V2ray配置指南](https://toutyrater.github.io/routing/sitedata.html)中v2ray只能识别程序目录下的dat的文件，如我有误解，还请指导！
> > 谢谢！
> 
> 通过指定环境变量路径

未来会考虑默认搜索路径增加 /usr/share/v2ray 之类的吗

**Comment by IceCodeNew** [comment]
> > > 想问一下如果存放到上述目录后，v2ray如何引用dat文件
> > > 目前根据脚本，dat文件会被下载到`/usr/local/lib/v2ray/`下，根据[V2ray配置指南](https://toutyrater.github.io/routing/sitedata.html)中v2ray只能识别程序目录下的dat的文件，如我有误解，还请指导！
> > > 谢谢！
> 
> 未来会考虑默认搜索路径增加 /usr/share/v2ray 之类的吗

我觉得这个很有必要，你可以在 v2fly/v2ray-core 那边开一个 issue 建议这个修改么？

**Comment by unknowndev233** [comment]
> > > > 想问一下如果存放到上述目录后，v2ray如何引用dat文件
> > > > 目前根据脚本，dat文件会被下载到`/usr/local/lib/v2ray/`下，根据[V2ray配置指南](https://toutyrater.github.io/routing/sitedata.html)中v2ray只能识别程序目录下的dat的文件，如我有误解，还请指导！
> > > > 谢谢！
> > 
> > 
> > 未来会考虑默认搜索路径增加 /usr/share/v2ray 之类的吗
> 
> 我觉得这个很有必要，你可以在 v2fly/v2ray-core 那边开一个 issue 建议这个修改么？
> @unknowndev233

可
