### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by PowerWordTree** [v2fly/fhs-install-v2ray#171]
ssh xxx.xxx 'bash <(curl https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21097  100 21097    0     0  19280      0  0:00:01  0:00:01 --:--:-- 19301
**tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified**
info: No new version. The current version of V2Ray is v4.31.0 .

**Comment by IceCodeNew** [comment]
It's not considered a bug.
Because this project is not designed to work in a non-interactive environment, to make the output more comfortable to read, the scripts' output is colored, which conflicts with the need for a script to be executed in a non-interactive environment without complaint.
