### ISSUE TITLE
请问在路由器环境下如和安装

### ISSUE THREAD

**Issue by victorxys** [v2fly/fhs-install-v2ray#173]
你好，我是在梅林固件的 ac66上安装v2ray的（其他方法试了很多，由于是mipel平台的，很多都不支持）
用了这个脚本，在路由器里面，但是报错了

admin@RT-AC66U-91E0:/tmp# bash <(curl -L https://raw.githubusercontent.com/v2fly
/fhs-install-v2ray/master/install-release.sh)
-sh: syntax error: unexpected "("

直接下载手动安装报这个错：
admin@RT-AC66U-91E0:/tmp# sh install-release.sh 
install-release.sh: line 112: syntax error: unexpected "("

请教一下如何安装，万分感谢

**Comment by IceCodeNew** [comment]
我本人也有一台安装梅林固件的华硕路由器，上面应该是不提供 root 权限的，更不会有 systemd 环境。
所以我不认为本项目适合用在路由器上去安装 v2ray。
