### ISSUE TITLE
remove卸载后没有同时删除配置文件/usr/local/etc/v2ray/config.json

### ISSUE THREAD

**Issue by 1265578519** [v2fly/fhs-install-v2ray#175]
remove卸载后没有同时删除配置文件/usr/local/etc/v2ray/config.json

**Comment by baiwenhao** [comment]
你的配置文件我看看呗

**Comment by IceCodeNew** [comment]
`echo 'info: If necessary, manually delete the configuration and log files.'`

脚本已经提示你手动卸载配置文件了，自动卸载配置文件恐怕又该有人不乐意了。
