### ISSUE TITLE
script translation to english, as the old script does not work anymore

### ISSUE THREAD

**Issue by firestorm99** [v2fly/fhs-install-v2ray#176]
see title.

Thx!

**Comment by IceCodeNew** [comment]
You got to make your point clearer. Currently, both scripts are English output prompts.
Are you looking for an English version of the Wiki of this project?

**Comment by firestorm99** [comment]
I checked again and found out that I confused it with: https://github.com/jinwyp/one_click_script

sorry for the mess. to be closed. ;-)
