### ISSUE TITLE
v2fly在后台运行半天后，会把cpu戳爆

### ISSUE THREAD

**Issue by sooxt98** [v2fly/fhs-install-v2ray#177]
本身用着dokodemo+vless xtls；如果直接在terminal运行v2ray没事，cpu最多5%而已，
但是如果是systemctl start v2ray，半天后cpu每个核就直接维持在50%

**Comment by kslr** [comment]
你这太玄学了，systemd不是用nobody呢

**Comment by IceCodeNew** [comment]
你这个提问完全没有给人帮忙的可能，我只能按照上游/第三方的问题做判断，然后关闭这个 issue。
如果你真的希望有人帮忙，首先你要尽可能给出排错信息。比如你是不是使用这个项目安装 v2ray，执行安装脚本前环境是不是干净的。过程中打印的提示信息是什么，你又是怎么处理的。
#63 的建议你也一条没做。

**Comment by sooxt98** [comment]
@IceCodeNew 没事，其实这问题对影响不大，我terminal用screen开着就是了，坐等哪天高人出现的时候，自会明白，题就自动解开了🙃

**Comment by sooxt98** [comment]
解: 如果你在4.23.1中使用TProxy并遇到了CPU 100%(or  SO_MARK > operation not permitted)的问题，可以在systemd文件中CapabilityBoundingSet属性添加CAP_NET_ADMIN
