### ISSUE TITLE
执行报错，以前的为什么不用了？

### ISSUE THREAD

**Issue by beijibingdong** [v2fly/fhs-install-v2ray#178]
[root@localhost v2ray]# bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by IceCodeNew** [comment]
`SSL certificate problem: self signed certificate in certificate chain`

删除掉系统上任何非发行版随附的根证书，或者 fork 本项目自行修改脚本中传递给 curl 的参数，让它不要检查证书。
这是你自己本地系统搞出的问题。

**Comment by beijibingdong** [comment]
谢谢
