### ISSUE TITLE
Should use arm32-v5 binaries on armv7l?

### ISSUE THREAD

**Issue by rprx** [v2fly/fhs-install-v2ray#181]
https://github.com/v2fly/fhs-install-v2ray/blob/d31559fcbb9447e6b1d26d03d0d6d95259d53957/install-release.sh#L64-L72

https://github.com/v2fly/v2ray-core/issues/280#issuecomment-710855263

还需要看一下树莓派和 armv6l 的情况

**Comment by IceCodeNew** [comment]
麻烦社区遇到这个问题的人测试下 develop 分支的最新脚本，然后在这里反馈结果。
