### ISSUE TITLE
对指定版本的支持？

### ISSUE THREAD

**Issue by sl179** [v2fly/fhs-install-v2ray#185]
鉴于当前v4.33.0 Remove XTLS，想到 ：
如果要安装v4.32.1等之前的版本或其他版本，没有类似nvm安装npm 那样便捷的方式----命令行指定特定版本号或手动指定就可以便捷地安装?

难道又得在vps本地修改脚本代码来支持？

**Comment by IceCodeNew** [comment]
https://github.com/v2fly/fhs-install-v2ray/blob/7c83cb4a1714a6349ea78f65d13194b83dcb9e93/install-release.sh#L490
