### ISSUE TITLE
请大佬帮看看我哪里配置错了吗？

### ISSUE THREAD

**Issue by cpyb** [v2fly/fhs-install-v2ray#188]
![systemctl status v2ray](https://user-images.githubusercontent.com/58124389/101571877-d73f3c00-3a12-11eb-83fa-20530d04fc75.JPG)
![V](https://user-images.githubusercontent.com/58124389/101568535-b0323b80-3a0d-11eb-8d72-e23695c0ee33.JPG)
![V2FLY-客户端](https://user-images.githubusercontent.com/58124389/101568585-c809bf80-3a0d-11eb-8aab-ad601bb6de9e.JPG)

重配服务器，发现旧安装方法失效，按照新的 白话文 教程 一步步配置后，systemctl status v2ray 看似乎正常（图1），但v2rayN 连不上。

v2rayN配置如（图3），还没配置域名。地址直接写的服务器ip。

port和id对应服务器上config.json（图2），端口已经放行。不知道还有哪里配置错了。

服务器时间已经校准，系统 Debian 9 x64 (stretch)。

谢谢。

**Comment by smallprogram** [comment]
貌似你服务器上根本没配置TLS，但是你客户端上开了TLS。

**Comment by cpyb** [comment]
> 貌似你服务器上根本没配置TLS，但是你客户端上开了TLS。

谢谢提醒，现在客户端上TLS关闭了，还是连不上


2020/12/09 11:44:47 tcp:127.0.0.1:9929 accepted tcp:www.google.com:443 [proxy] 
2020/12/09 11:44:48 tcp:127.0.0.1:9932 accepted tcp:www.google.com:443 [proxy] 
2020/12/09 11:44:48 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/12/09 11:44:49 tcp:127.0.0.1:9935 accepted tcp:www.google.com:443 [proxy] 
2020/12/09 11:44:49 tcp:127.0.0.1:9936 accepted tcp:www.google.com:443 [proxy] 
2020/12/09 11:44:50 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/12/09 11:44:56 tcp:127.0.0.1:9939 accepted tcp:www.google.com:443 [proxy] 
2020/12/09 11:44:58 tcp:127.0.0.1:9942 accepted tcp:clients4.google.com:443 [proxy] 
2020/12/09 11:44:58 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/12/09 11:44:59 tcp:127.0.0.1:9945 accepted tcp:www.google.com:443 [proxy] 
2020/12/09 11:44:59 tcp:127.0.0.1:9946 accepted tcp:clients4.google.com:443 [proxy] 
2020/12/09 11:45:00 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/12/09 11:45:01 tcp:127.0.0.1:9949 accepted tcp:oauthaccountmanager.googleapis.com:443 [proxy]

**Comment by smallprogram** [comment]
### v2ray vmess TCP配置
1. 首先，确认你**服务器Debian 9的时间是否与本地时间一致**。如果不一致做出修改。修改方法网上查一下很多
2. 修改服务器 /usr/local/etc/v2ray/config.json内容，记得把红色注释内容删掉，防止出现未知错误：
```json
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 1234,  // 修改为你自己想要设置的端口，客户端也要设置为这个端口
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "27848739-7e62-4138-9fd3-098a63964b6b",  // 改为你自己想要改的uuid
                        "level": 0,
                        "alterId": 0,  // 改不改都行。默认0就挺好
                        "email": "user@domain.com"  // 改为你自己想要改的东西。这个主要用在流量统计时的标识
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp"
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ],
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "block"
            }
        ]
    },
}
```
3. 重启v2ray。`service v2ray restart`
4. 使用v2rayN尝试链接。

其实还是推荐vless tcp模式，速度快。高端点用vless tcp xtls,这个需要xray。

**Comment by IceCodeNew** [comment]
如何配置是上游的问题，请前往 v2fly/v2ray-core 项目 Issue 区提问。
