### ISSUE TITLE
fhs脚本安装遭遇The current version of V2Ray is  . 版本为空的问题

### ISSUE THREAD

**Issue by syouko** [v2fly/fhs-install-v2ray#189]
1，使用 fhs 脚本  --remove  以后，手动清除了 所有相关目录

2，使用 fhs 脚本进行 安裝執行檔和 .dat 資料檔

被提示：
info: No new version. The current version of V2Ray is  .

经过群内协助排查，
发现脚本第229行 https://github.com/v2fly/fhs-install-v2ray/blob/master/install-release.sh#L229
获取到的API为

{"message":"API rate limit exceeded for 我的IP. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}

确认 是我的 IP 调用 github api 次数太多导致

浏览器直接访问 https://api.github.com 遭遇同样的提示

目前暂时在终端挂代理解决

export https_proxy=http://IP:PORT

挂完后 curl https://api.github.com 如没有之前的提示，就OK了

**Comment by U-v-U** [comment]
GitHub 对未登录的 API 请求有严格的数量限制
https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#rate-limiting
