### ISSUE TITLE
包管理器的判断缺陷导致 arch 系使用此脚本报错

### ISSUE THREAD

**Issue by PaPerseller** [v2fly/fhs-install-v2ray#19]
manjaro 使用此脚本时报错 The script does not support the package manager in this operating system，而旧版 go.sh 虽然判断方式类似，但仍可进行安装流程。目前只能将脚本下载至本地，并删除
        if [[ "$(command -v apt)" ]]; then
            PACKAGE_MANAGEMENT_INSTALL='apt install'
            PACKAGE_MANAGEMENT_REMOVE='apt remove'
        elif [[ "$(command -v yum)" ]]; then
            PACKAGE_MANAGEMENT_INSTALL='yum install'
            PACKAGE_MANAGEMENT_REMOVE='yum remove'
            if [[ "$(command -v dnf)" ]]; then
                PACKAGE_MANAGEMENT_INSTALL='dnf install'
                PACKAGE_MANAGEMENT_REMOVE='dnf remove'
            fi
        elif [[ "$(command -v zypper)" ]]; then
            PACKAGE_MANAGEMENT_INSTALL='zypper install'
            PACKAGE_MANAGEMENT_REMOVE='zypper remove'
        else
            echo "error: The script does not support the package manager in this operating system."
            exit 1
部分才能成功使用。

**Comment by dctxmei** [comment]
Manjaro 可以通過 `pacman` 直接安裝 `v2ray` 包，不需要使用此腳本。
