### ISSUE TITLE
V2ray 启动问题

### ISSUE THREAD

**Issue by naoko8964** [v2fly/fhs-install-v2ray#191]
我照着 [旧脚本迁移](https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this) 完成了新版本的安装后。
输入 `v2ray --config=/etc/v2ray/config.json`
输出
`V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 linux/amd64)
A unified platform for anti-censorship.`
`panic: open /usr/local/etc/v2rayconfig.json: no such file or directory`

`goroutine 1 [running]:`
`v2ray.com/core/common.Must(...)`
	`v2ray.com/core/common/common.go:26`
`v2ray.com/core/main/jsonem.init.0.func1(0xd00840, 0xc0001a8ba0, 0x7ffd9abd57ac, 0x4, 0xc000075b60)`
	`v2ray.com/core/main/jsonem/jsonem.go:25 +0x44d`
`v2ray.com/core.LoadConfig(0xe53636, 0x4, 0x7ffd9abd5791, 0x1f, 0xd00840, 0xc0001a8ba0, 0xc000129e98, 0xc5b426, 0xf68900)`
	`v2ray.com/core/config.go:66 +0x262`
`main.startV2Ray(0xc0000642a0, 0xc00000c070, 0x1, 0x1)`
	`v2ray.com/core/main/main.go:114 +0x145`
`main.main()`
	`v2ray.com/core/main/main.go:143 +0xb1`

输入 `v2ray --config=/usr/local/etc/v2rayconfig.json`
无输出。

而后 `service v2ray start`
输出 `Redirecting to /bin/systemctl start v2ray.service`
`Failed to start v2ray.service: Unit v2ray.service not found.`

配置文件是老脚本的正确的。目前config.json放在了/usr/local/etc/v2ray
而/etc内无/v2ray文件夹。

**我应该怎么做才能正常启动v2ray呢？**

顺带一提 输入 
`bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)` 
后正常显示 `info: No new version. The current version of V2Ray is v4.33.0`

**Comment by kslr** [comment]
>  panic: open /usr/local/etc/v2rayconfig.json: no such file or directory

**Comment by naoko8964** [comment]
to @kslr ![](https://raw.githubusercontent.com/naoko8964/img/main/1.PNG)
那个，这边是有放进去的。

**Comment by IceCodeNew** [comment]
你没注意到报错信息里提示你路径少了一个斜杠吗？

**Comment by naoko8964** [comment]
to @IceCodeNew ......还是搞不好。
把`v2rayconfig.json`丢到`/usr/local/etc/`
`# v2ray --config=/etc/v2ray/config.json`
`panic: open /etc/v2ray/config.json: no such file or directory`

再把`config.json`丢到`/etc/v2ray/`
`# v2ray --config=/etc/v2ray/config.json`
只输出
`V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 linux/amd64)`
`A unified platform for anti-censorship.`
`2021/01/03 [Info] v2ray.com/core/main/jsonem: Reading config: /etc/v2ray/config.json`
`2021/01/03 [Warning] v2ray.com/core: V2Ray 4.33.0 started`

这算启动了吗。还是说卡住了？
`# service v2ray start`
`Redirecting to /bin/systemctl start v2ray.service
Failed to start v2ray.service: Unit v2ray.service not found.
`

`# v2ray start`
`V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 linux/amd64)`
`A unified platform for anti-censorship.`
`2021/01/03 Using config from STDIN`
`2021/01/03 [Info] v2ray.com/core/main/jsonem: Reading config: stdin:`

请问我现在应该怎么办？

**Comment by naoko8964** [comment]
已解決。虽然那些路径报错还没搞定
