### ISSUE TITLE
安装异常

### ISSUE THREAD

**Issue by FlagGuarder** [v2fly/fhs-install-v2ray#192]
当我使用 bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-dat-release.sh) 命令进行安装时，我受到了提示，0curl: (7) Failed to connect to raw.githubusercontent.com port 443: 拒绝连接
请问这是什么情况

**Comment by DuckSoft** [comment]
墙

**Comment by benjaminchodroff** [comment]
It would be ideal if there were prepackaged releases that we could download and then have an option to copy to our server and install "offline"

**Comment by IceCodeNew** [comment]
> It would be ideal if there were prepackaged releases that we could download and then have an option to copy to our server and install "offline"

https://github.com/v2fly/fhs-install-v2ray/blob/a24fe6823b02e2f1780e4d7845353bf84531e038/install-release.sh#L502

**Comment by benjaminchodroff** [comment]
@IceCodeNew Thanks, but would you mind updating the Readme instructions to be more clear? 
1. Download the latest v2ray version: https://github.com/v2fly/v2ray-core/releases/download/v4.34.0/v2ray-linux-64.zip
2. Download this repository as a zip file
3. Send both zip files to your server
4. unzip fhs-install-v2ray-master.zip; cd fhs-install-v2ray-master
5. bash install-release.sh -l v2ray-linux-64.zip

**Comment by IceCodeNew** [comment]
> @IceCodeNew Thanks, but would you mind updating the Readme instructions to be more clear? 
> 1. Download the latest v2ray version: https://github.com/v2fly/v2ray-core/releases/download/v4.34.0/v2ray-linux-64.zip
> 2. Download this repository as a zip file
> 3. Send both zip files to your server
> 4. unzip fhs-install-v2ray-master.zip; cd fhs-install-v2ray-master
> 5. bash install-release.sh --local v2ray-linux-64.zip

PR welcome.
