### ISSUE TITLE
Ubuntu 18.04 installation exception

### ISSUE THREAD

**Issue by cloudseasail** [v2fly/fhs-install-v2ray#196]
`~$ sudo bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
bash: /dev/fd/63: No such file or directory   `

**Comment by cloudseasail** [comment]
https://github.com/233boy/v2ray/issues/181#
搜到解决办法了，要进root，不能sudo，这个问题还没解决吗

**Comment by IceCodeNew** [comment]
> [233boy/v2ray#181](https://github.com/233boy/v2ray/issues/181)
> 搜到解决办法了，要进root，不能sudo，这个问题还没解决吗

```
sudo -i
bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
```
