### ISSUE TITLE
添加force local install参数

### ISSUE THREAD

**Issue by Diavo1o** [v2fly/fhs-install-v2ray#2]
如题。譬如在反向代理情景中，要更新内网设备（家用宽带）的V2Ray时十分困难，一来github下载严重延迟，二来如果操作失误就完全无法通过远端访问内网设备。

一些操作失误的例子如下

1. 通过--local 参数更新V2Ray会因systemctl stop v2ray命令运行后断掉SSH远端访问，后续命令无法执行

2. 通过添加 /root/install-release.sh --local v2ray.zip到/etc/rc.local，然后reboot重新更新也失败，无法通过SSH远端访问内网设备（虽然最后靠断电重新开启设备暂时解决了）

故此，希望能添加force local install参数，在忽略任何警告情况以及不中断下运行install-release.sh，更新v2ray

**Comment by nicholascw** [comment]
那你一定要走 V2Ray 连 SSH 的话 本地把 systemctl stop 注释掉不就好了嘛。。
