### ISSUE TITLE
运行脚本时可选择不更新 geosite.dat 和 geoip.dat

### ISSUE THREAD

**Issue by CalmLong** [v2fly/fhs-install-v2ray#20]
如题，希望可以添加个参数能让 `geosite.dat` 和 `geoip.dat` 不跟随 V2Ray 更新。

原因

自定义了 `geosite.dat` 和 `geoip.dat` 并且名字也是用的 `geosite` 和 `geoip`，使用脚本更新时会被一同覆盖。
虽然可以改名字并在配置文件中使用 `ext` 解决，但是这样还是会多出来两个文件并且还用不到

**Comment by dctxmei** [comment]
在 `/usr/local/lib/v2ray/` 下創建一個名為 `.undat` 的文件，此文件存在，則腳本不更新 geoip.dat 和 geosite.dat。

這樣如何呢？

**Comment by CalmLong** [comment]
可以，这样就不用指定参数了，支持~~

**Comment by dctxmei** [comment]
已完成修改。

**Comment by CalmLong** [comment]
感谢。已测试可用
