### ISSUE TITLE
可以指定安装的版本吗

### ISSUE THREAD

**Issue by VolinHe** [v2fly/fhs-install-v2ray#200]
RT

**Comment by kslr** [comment]
你可以下载指定的 release 版本，然后通过本地安装

**Comment by IceCodeNew** [comment]
https://github.com/v2fly/fhs-install-v2ray/blob/a24fe6823b02e2f1780e4d7845353bf84531e038/install-release.sh#L498

**Comment by VolinHe** [comment]
> https://github.com/v2fly/fhs-install-v2ray/blob/a24fe6823b02e2f1780e4d7845353bf84531e038/install-release.sh#L498

I see, thank you
