### ISSUE TITLE
安装错误：warning: The systemd version on the current operating system is too low

### ISSUE THREAD

**Issue by ghq200101** [v2fly/fhs-install-v2ray#202]
vps操作系统是debian 9,哪位老师帮忙看一下呢：

![123](https://user-images.githubusercontent.com/9986859/111058149-63a44380-84c7-11eb-994a-2fd8879e9159.png)

**Comment by IceCodeNew** [comment]
这只是 warning 而已，并不是 error，不代表脚本执行错误。
但你确实可以考虑升级到 Debian 10 了（Debian 11 都快发布了）

**Comment by ghq200101** [comment]
安装没有port和uuid,运行看似正常，但无法上网。

**Comment by IceCodeNew** [comment]
> 安装没有port和uuid,运行看似正常，但无法上网。

https://github.com/v2fly/fhs-install-v2ray/issues/61#issuecomment-675525711

**Comment by ghq200101** [comment]
![123](https://user-images.githubusercontent.com/9986859/111650345-2aa9fd00-8840-11eb-892b-35171fe0547a.png)
@IceCodeNew 还是无法上网

**Comment by dumpload** [comment]
同样的问题，启动后端口没有开起来

**Comment by IceCodeNew** [comment]
> 同样的问题，启动后端口没有开起来

安装问题在这里提 issue，使用问题去 v2fly/v2ray-core 提 issue
不要随便找到一个 issue 就挖坟好吗？你的问题和这里的问题是同一个问题吗？
