### ISSUE TITLE
不知道什么问题,,执行失败

### ISSUE THREAD

**Issue by 1965514404** [v2fly/fhs-install-v2ray#203]
[root@VM-12-14-centos ~]# bash go.sh
ERROR: This script has been DISCARDED, please switch to fhs-install-v2ray project.
HOW TO USE: https://github.com/v2fly/fhs-install-v2ray
TO MIGRATE: https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this

**Comment by database64128** [comment]
Please learn to read.
