### ISSUE TITLE
read soft link config.json alert no permission

### ISSUE THREAD

**Issue by zyf0330** [v2fly/fhs-install-v2ray#209]
On Ubuntu, clean install and ln -s config.json to /usr/local/etc/v2ray/config.json.
Then systemctl start v2ray.service, journalctl alerts that 
```
Jul 02 10:59:45  v2ray[289680]: 2021/07/02 10:59:45 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
Jul 02 10:59:45  v2ray[289680]: panic: open /usr/local/etc/v2ray/config.json: permission denied
```

**Comment by IceCodeNew** [comment]
> ln -s config.json to /usr/local/etc/v2ray/config.json.

Please give the specific command you have issued.

Also, you should follow issue #63 and give us more info about your environment.

**Comment by zenmaster-cd** [comment]
use ls -alF --color=auto /usr/local/etc/v2ray or ls - config.json
Check config.josn whether other users have read permissions
-rwxr--**r**--   config.json*
