### ISSUE TITLE
v2ray 4.40.1 /usr/local/bin/v2ray Failed to execute command: No such file or directory 

### ISSUE THREAD

**Issue by ToTdate** [v2fly/fhs-install-v2ray#210]
Debian 10 v2ray 4.40.1

// v2ray 安装日志

Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.40.1/v2ray-linux-64.zip.dg st
info: Extract the V2Ray package to /tmp/tmp.X8WLXRjiqg and prepare it for installation.
rm: cannot remove '/etc/systemd/system/v2ray.service.d/10-donot_touch_multi_conf.conf': No such file or directory
rm: cannot remove '/etc/systemd/system/v2ray@.service.d/10-donot_touch_multi_conf.conf': No such file or directory
info: Systemd service files have been installed successfully!
warning: The following are the actual parameters for the v2ray service startup.
warning: Please make sure the configuration file path is correctly set.
/etc/systemd/system/v2ray.service
[Unit]
Description=V2Ray Service
Documentation=https://www.v2fly.org/
After=network.target nss-lookup.target

[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
Restart=on-failure
RestartPreventExitStatus=23

[Install]
WantedBy=multi-user.target
/etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
In case you have a good reason to do so, duplicate this file in the same directory and make your customizes there.
Or all changes you made will be lost! # Refer: https://www.freedesktop.org/software/systemd/man/systemd.unit.html
[Service]
ExecStart=
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json

installed: /usr/local/bin/v2ray
installed: /usr/local/bin/v2ctl
installed: /usr/local/share/v2ray/geoip.dat
installed: /usr/local/share/v2ray/geosite.dat
installed: /etc/systemd/system/v2ray.service
installed: /etc/systemd/system/v2ray@.service
removed: /tmp/tmp.X8WLXRjiqg
info: V2Ray v4.40.1 is installed.
You may need to execute a command to remove dependent software: apt purge curl unzip

// v2ray 运行日志

root@sv-486 :~# service v2ray status
● v2ray.service - V2Ray Service
Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
Drop-In: /etc/systemd/system/v2ray.service.d
└─10-donot_touch_single_conf.conf
Active: failed (Result: exit-code) since Tue 2021-07-06 23:41:24 CST; 7s ago
Docs: https://www.v2fly.org/
Process: 16675 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json (code=exited, status=203/EXEC)
Main PID: 16675 (code=exited, status=203/EXEC)

Jul 06 23:41:24 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jul 06 23:41:24 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Jul 06 23:41:24 sv-486 systemd[1]: Stopped V2Ray Service.
Jul 06 23:41:24 sv-486 systemd[1]: v2ray.service: Start request repeated too quickly.
Jul 06 23:41:24 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 06 23:41:24 sv-486 systemd[1]: Failed to start V2Ray Service.

// v2ray服务异常日志如下

root@sv-486:~# journalctl -u v2ray
-- Logs begin at Mon 2021-07-05 11:03:19 CST, end at Tue 2021-07-06 23:41:24 CST. --
Jul 05 12:03:09 sv-486 systemd[1]: Started V2Ray Service.
Jul 05 12:03:09 sv-486 systemd[13777]: v2ray.service: Failed to execute command: No such file or directory
Jul 05 12:03:09 sv-486 systemd[13777]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: No s
Jul 05 12:03:09 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Jul 05 12:03:09 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 05 12:03:09 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jul 05 12:03:09 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 1.
Jul 05 12:03:09 sv-486 systemd[1]: Stopped V2Ray Service.
Jul 05 12:03:09 sv-486 systemd[1]: Started V2Ray Service.
Jul 05 12:03:09 sv-486 systemd[13778]: v2ray.service: Failed to execute command: No such file or directory
Jul 05 12:03:09 sv-486 systemd[13778]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: No s
Jul 05 12:03:09 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Jul 05 12:03:09 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 05 12:03:10 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jul 05 12:03:10 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 2.
Jul 05 12:03:10 sv-486 systemd[1]: Stopped V2Ray Service.
Jul 05 12:03:10 sv-486 systemd[1]: Started V2Ray Service.
Jul 05 12:03:10 sv-486 systemd[13779]: v2ray.service: Failed to execute command: No such file or directory
Jul 05 12:03:10 sv-486 systemd[13779]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: No s
Jul 05 12:03:10 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Jul 05 12:03:10 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.

**Comment by IceCodeNew** [comment]
It seems to be clear out while suspecting the installation process in the first place.
You need to follow #63 and provide more information so we can help you.

**Comment by ToTdate** [comment]
journalctl --boot -u v2ray
-- Logs begin at Wed 2021-07-07 19:06:49 CST, end at Wed 2021-07-07 19:44:14 CST. --
Jul 07 19:06:52 sv-486 systemd[1]: Started V2Ray Service.
Jul 07 19:06:52 sv-486 systemd[404]: v2ray.service: Failed to execute command: Permission denied
Jul 07 19:06:52 sv-486 systemd[404]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: Permission denied
Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 1.
Jul 07 19:06:53 sv-486 systemd[1]: Stopped V2Ray Service.
Jul 07 19:06:53 sv-486 systemd[1]: Started V2Ray Service.
Jul 07 19:06:53 sv-486 systemd[433]: v2ray.service: Failed to execute command: Permission denied
Jul 07 19:06:53 sv-486 systemd[433]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: Permission denied
Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 2.
Jul 07 19:06:53 sv-486 systemd[1]: Stopped V2Ray Service.
Jul 07 19:06:53 sv-486 systemd[1]: Started V2Ray Service.
Jul 07 19:06:53 sv-486 systemd[438]: v2ray.service: Failed to execute command: Permission denied
Jul 07 19:06:53 sv-486 systemd[438]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: Permission denied
Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 3.
Jul 07 19:06:54 sv-486 systemd[1]: Stopped V2Ray Service.
Jul 07 19:06:54 sv-486 systemd[1]: Started V2Ray Service.
Jul 07 19:06:54 sv-486 systemd[440]: v2ray.service: Failed to execute command: Permission denied
Jul 07 19:06:54 sv-486 systemd[440]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: Permission denied
Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 4.
Jul 07 19:06:54 sv-486 systemd[1]: Stopped V2Ray Service.
Jul 07 19:06:54 sv-486 systemd[1]: Started V2Ray Service.
Jul 07 19:06:54 sv-486 systemd[442]: v2ray.service: Failed to execute command: Permission denied
Jul 07 19:06:54 sv-486 systemd[442]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: Permission denied
Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Jul 07 19:06:54 sv-486 systemd[1]: Stopped V2Ray Service.
Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Start request repeated too quickly.
Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 07 19:06:54 sv-486 systemd[1]: Failed to start V2Ray Service.

**Comment by IceCodeNew** [comment]
> journalctl --boot -u v2ray
> -- Logs begin at Wed 2021-07-07 19:06:49 CST, end at Wed 2021-07-07 19:44:14 CST. --
> Jul 07 19:06:52 sv-486 systemd[1]: Started V2Ray Service.
> Jul 07 19:06:52 sv-486 systemd[404]: v2ray.service: Failed to execute command: Permission denied
> Jul 07 19:06:52 sv-486 systemd[404]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: Permission denied
> Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
> Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
> Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
> Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 1.
> Jul 07 19:06:53 sv-486 systemd[1]: Stopped V2Ray Service.
> Jul 07 19:06:53 sv-486 systemd[1]: Started V2Ray Service.
> Jul 07 19:06:53 sv-486 systemd[433]: v2ray.service: Failed to execute command: Permission denied
> Jul 07 19:06:53 sv-486 systemd[433]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: Permission denied
> Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
> Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
> Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
> Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 2.
> Jul 07 19:06:53 sv-486 systemd[1]: Stopped V2Ray Service.
> Jul 07 19:06:53 sv-486 systemd[1]: Started V2Ray Service.
> Jul 07 19:06:53 sv-486 systemd[438]: v2ray.service: Failed to execute command: Permission denied
> Jul 07 19:06:53 sv-486 systemd[438]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: Permission denied
> Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
> Jul 07 19:06:53 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
> Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
> Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 3.
> Jul 07 19:06:54 sv-486 systemd[1]: Stopped V2Ray Service.
> Jul 07 19:06:54 sv-486 systemd[1]: Started V2Ray Service.
> Jul 07 19:06:54 sv-486 systemd[440]: v2ray.service: Failed to execute command: Permission denied
> Jul 07 19:06:54 sv-486 systemd[440]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: Permission denied
> Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
> Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
> Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
> Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 4.
> Jul 07 19:06:54 sv-486 systemd[1]: Stopped V2Ray Service.
> Jul 07 19:06:54 sv-486 systemd[1]: Started V2Ray Service.
> Jul 07 19:06:54 sv-486 systemd[442]: v2ray.service: Failed to execute command: Permission denied
> Jul 07 19:06:54 sv-486 systemd[442]: v2ray.service: Failed at step EXEC spawning /usr/local/bin/v2ray: Permission denied
> Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
> Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
> Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
> Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
> Jul 07 19:06:54 sv-486 systemd[1]: Stopped V2Ray Service.
> Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Start request repeated too quickly.
> Jul 07 19:06:54 sv-486 systemd[1]: v2ray.service: Failed with result 'exit-code'.
> Jul 07 19:06:54 sv-486 systemd[1]: Failed to start V2Ray Service.

Follow the #63, make sure you had read the instructions carefully.
Or I won't waste my time trying to help.

**Comment by plagao** [comment]
fork/exec /usr/local/bin/v2ray: no such file or directory

**Comment by IceCodeNew** [comment]
> fork/exec /usr/local/bin/v2ray: no such file or directory

Please open another issue and follow the suggestions in #63
