### ISSUE TITLE
Receiving HTTP scans for /gaocc/g445g

### ISSUE THREAD

**Issue by szepeviktor** [v2fly/fhs-install-v2ray#214]
Hello! I'm not a v2ray user.
The HTTP request targeting my websites looks like this.

```
GET /gaocc/g445g HTTP/1.1
```

I've read [on a forum](https://hostloc.com/forum.php?mod=redirect&goto=findpost&ptid=859693&pid=10557299)

> GitHub搜了一下，目测是某个v2ray安装脚本默认路径

(GitHub searched, visual inspection is a V2RAY installation script default path)

Was `/gaocc/g445g` every v2ray's default path?

Thank you!

**Comment by IceCodeNew** [comment]
> Hello! I'm not a v2ray user.
> The HTTP request targeting my websites looks like this.
> 
> ```
> GET /gaocc/g445g HTTP/1.1
> ```
> 
> I've read [on a forum](https://hostloc.com/forum.php?mod=redirect&goto=findpost&ptid=859693&pid=10557299)
> 
> > GitHub搜了一下，目测是某个v2ray安装脚本默认路径
> 
> (GitHub searched, visual inspection is a V2RAY installation script default path)
> 
> Was `/gaocc/g445g` every v2ray's default path?
> 
> Thank you!
> 

Nop. the official v2ray project has ceased distributing default configuration for good.
