### ISSUE TITLE
V2Ray 服务启连接不上

### ISSUE THREAD

**Issue by leonardean** [v2fly/fhs-install-v2ray#215]
我使用了 `bash <(curl -L -s https://git.io/v2ray_ss.sh)`这个命令在Azure VM Ubuntu 20上安装了V2Ray服务，里面包括了`bash <(curl -L -s https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)`的调用。在服务启动后短时间内（几小时）是好用的，几小时后就连接不上了，但是如果我给这个服务换一个端口，又可以正常运行一段时间，然后又再次不可用。。。请问这是什么原因。

**Comment by IceCodeNew** [comment]
请咨询第三方和 v2ray-core 上游项目。

**Comment by okamoto007** [comment]
八成是已经被GFW盯上了，端口换的频繁的话估计IP都要凉
