### ISSUE TITLE
Win10 v2rayN 客户端测速提示远程服务器返回错误：（503）服务器不可用

### ISSUE THREAD

**Issue by hmf17** [v2fly/fhs-install-v2ray#216]
config.json如下

> 
        "log": {
                "access": "/var/log/v2ray/access.log",
                "error": "/var/log/v2ray/error.log",
                "loglevel": "warning"
        },
        "inbounds": [
                {
                        "port": 8880,
                        "protocol": "vmess",
                        "settings": {
                                "clients": [
                                        {
                                                "id": "da5c5b2d-06ca-4363-9b4d-3a9e23ce291d",
                                                "level": 1,
                                                "alterId": 64
                                        }
                                ]
                        },
                        "streamSettings": {
                                "network": "ws"
                        },
                        "sniffing": {
                                "enabled": true,
                                "destOverride": [
                                        "http",
                                        "tls"
                                ]
                        }
                }
                //include_ss
                //include_socks
                //include_mtproto
                //include_in_config
                //
        ],
        "outbounds": [
                {
                        "protocol": "freedom",
                        "settings": {}
                },
                {
                        "protocol": "blackhole",
                        "settings": {},
                        "tag": "blocked"
                },
                {
                        "protocol": "freedom",
                        "settings": {},
                        "tag": "direct"
                },
                {
                        "protocol": "mtproto",
                        "settings": {},
                        "tag": "tg-out"
                }
                //include_out_config
                //
        ],
        "dns": {
                "server": [
                        "8.8.8.8",
                        "1.1.1.1",
                        "localhost"
                ]
        },
        "routing": {
                "domainStrategy": "IPOnDemand",
                "rules": [
                        {
                                "type": "field",
                                "ip": [
                                        "0.0.0.0/8",
                                        "10.0.0.0/8",
                                        "100.64.0.0/10",
                                        "127.0.0.0/8",
                                        "169.254.0.0/16",
                                        "172.16.0.0/12",
                                        "192.0.0.0/24",
                                        "192.0.2.0/24",
                                        "192.168.0.0/16",
                                        "198.18.0.0/15",
                                        "198.51.100.0/24",
                                        "203.0.113.0/24",
                                        "::1/128",
                                        "fc00::/7",
                                        "fe80::/10"
                                ],
                                "outboundTag": "blocked"
                        },
                        {
                                "type": "field",
                                "inboundTag": ["tg-in"],
                                "outboundTag": "tg-out"
                        }
                        //include_ban_ad
                        //include_rules
                        //
                ]
        },
        "transport": {
                "kcpSettings": {
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": false
        },
                "sockopt": {
                        "tcpFastOpen": true
                }
        }

配置也是从issue中找到的，然后添加在客户端的配置如下，请问有什么问题吗？
![Uploading 捕获.JPG…]()

**Comment by IceCodeNew** [comment]
请在上有提问，并对配置文件脱敏。
