### ISSUE TITLE
[Feature Request] Arch Linux support.

### ISSUE THREAD

**Issue by kinggx9** [v2fly/fhs-install-v2ray#219]
I use a personal server (arch-systemd)
I tried setting (log):
wget https://github.com/v2ray/v2ray-core/releases/download/v4.16.0/v2ray-linux-64.zip 

unzip v2ray*.zip
cp vpoint_vmess_freedom.json /etc/v2ray/config.json
mkdir /var/log/v2ray/
mkdir /etc/v2ray /usr/bin/v2ray /var/log/v2ray
sudo chmod +x v2ray v2ctl
sudo mv v2ray v2ctl geoip.dat geosite.dat -t /usr/bin/v2ray
touch /etc/v2ray/config.json

gedit /etc/v2ray/config.json

=> UUID: https://www.uuidgenerator.net/
62ee5142-14f0-11ec-82a8-0242ac130003

sudo mv systemd/v2ray.service /etc/systemd/system/
sudo systemctl enable v2ray

Can you tell me how to improve?

**Comment by IceCodeNew** [comment]
0. Have you utilized this project for setting up v2ray?
---
> Can you tell me how to improve?
1. How is your deployment? Does it work or not?
---
2. Follow #63
