### ISSUE TITLE
支持ubuntu

### ISSUE THREAD

**Issue by temper10** [v2fly/fhs-install-v2ray#220]
目前ubuntu 運行會遇到這個錯誤：

`curl: (23) Failed writing body (481 != 1378)`

20.04

**Comment by IceCodeNew** [comment]
Follow #63 
---
我就是主要在 Ubuntu 20.04 平台上做的测试，所以支持一定是没问题的。
你这个提问实在不得要点，我只能说我初步的判断是
1. 网络问题，下到一半连接断开了（走代理、换个网络或者多试几次

**Comment by anspipi** [comment]
我也遇到同样的错误。版本 也是 20.04，请问怎么解决？

$ sudo bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
bash: /dev/fd/63: No such file or directory
admin@localhost:~$   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 23 21647   23  4993    0     0  23115      0 --:--:-- --:--:-- --:--:-- 23223
curl: (23) Failed writing body (481 != 1378)

**Comment by IceCodeNew** [comment]
> 我也遇到同样的错误。版本 也是 20.04，请问怎么解决？
> 
> $ sudo bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
> bash: /dev/fd/63: No such file or directory
> admin@localhost:~$   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>  23 21647   23  4993    0     0  23115      0 --:--:-- --:--:-- --:--:-- 23223
> curl: (23) Failed writing body (481 != 1378)
> 

sudo -i 切换用户环境，再执行脚本。提问前先搜索 issue 区

**Comment by luozhongxiangsi** [comment]
我也是ubuntu 20.04,无论是普通用户还是root用户执行都没有成功过

**Comment by pnxtm** [comment]
I also encountered the same error. The workaround is downloading it and manually executing it.
