### ISSUE TITLE
是否可以在README中增加离线安装的相关内容

### ISSUE THREAD

**Issue by Eriri-i** [v2fly/fhs-install-v2ray#226]
>1. Download the latest v2ray version: https://github.com/v2fly/v2ray-core/releases/download/v4.34.0/v2ray-linux-64.zip
>2. Download this repository as a zip file
>3. Send both zip files to your server
>4. unzip fhs-install-v2ray-master.zip; cd fhs-install-v2ray-master
>5. bash install-release.sh --local v2ray-linux-64.zip
>
>_Originally posted by @benjaminchodroff in https://github.com/v2fly/fhs-install-v2ray/issues/192#issuecomment-767597828_

**Comment by IceCodeNew** [comment]
I have no interest in putting this part of instruction into README. However, PR is welcomed.
If you wonder why, here is my opinion:
Doing offline installation will need users to understand exactly how this project's script works, which means users should know the operating procedures for doing so by viewing this project's script.
