### ISSUE TITLE
centos7 上面可以安装v2ary客户端吗

### ISSUE THREAD

**Issue by sevenNightL** [v2fly/fhs-install-v2ray#227]
如题，centos7怎么安装v2ray客户端呢？有相关文档吗？安装之后怎么通过订阅连接配置http代理呢

**Comment by IceCodeNew** [comment]
1. 本项目支持 centos 7 系统。
2. 能找到并理解上游官方文档是使用本项目的前提条件。该项目如何使用的指南也包括在其中。
3. 请向上游项目询问。提问之前先搜索。
