### ISSUE TITLE
v2ray配置无报错，一使用就会卡住（推测

### ISSUE THREAD

**Issue by zehuichen123** [v2fly/fhs-install-v2ray#228]
这个bug有些让我摸不着头脑 所以抱着试试的心态开的issue，之前都是用的一件脚本
是这样的，我在vultr租的vps，系统为ubuntu 18/21都试过，在上面配置了服务端，具体的配置文件为
```
{
  "inbounds": [
    {
      "port": 49989, // 服务器监听端口
      "protocol": "vmess",    // 主传入协议
      "settings": {
        "clients": [
          {
            "id": "fe16debf-855d-41fa-9d88-964c974be264",  // 用户 ID，客户端与服务器必须相同
            "alterId": 233            //这里我64，128都尝试了...
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",  // 主传出协议
      "settings": {}
    }
  ]
}
```
同时时间也校准了
```
root@vultr:~# date -R
Thu, 11 Nov 2021 22:40:19 +0800
```
理论上应该这样服务端就ok了？
客户端这边我是直接用的shadowrocket，类似这样
<img src="https://user-images.githubusercontent.com/24351120/141317101-e283e787-7c5b-4112-a90f-20dccbf165a0.jpeg"  height = "500">
这个时候我去点连通性测试都是正常的 大概100～1000ms不等的延迟，但是不会存在超时的情况（update一下 发现有时候也会超时，但是下一次一般能连上），如果此时我在手机上访问google，会直接失败（无法访问此网站），然后此时再点连通性测试一直都是超时，大概等5min左右又能够重新恢复正常连通性测试，但是依然无法登陆google。我更换了几台vps都是一样的结果。
如果是在电脑上用v2rayX的话 我能够在一瞬间打开google，但是是一次性的，之后就访问不到了，这个时候用手机的连通性测试也会超时，然后过5分钟 再用就又可以连一次google，然后挂掉...
所以我感觉是v2ray服务端这边哪里卡住或者出错了？还是我配置有啥问题吗？orz 看了大佬整理的文档 但是没有找到相关的问题

**Comment by IceCodeNew** [comment]
请前往上游提问。本项目只解决安装问题。
另外，提问时请给配置文件中敏感信息做打码/替换处理。
