### ISSUE TITLE
安装脚本能否支持 OpenWrt ?

### ISSUE THREAD

**Issue by qifei** [v2fly/fhs-install-v2ray#229]
我看 Release 能支持 OpenWrt，但是安装脚本在 OpenWrt 命令行下 安装失败，提示没有 systemd。

**Comment by IceCodeNew** [comment]
不支持。

https://github.com/v2fly/fhs-install-v2ray/issues/223#issuecomment-946651732

**Comment by qifei** [comment]
谢谢你的回答。
我运行过，也知道不支持。
OpenWrt 是很常见的系统，路由翻墙几乎都要用到。
是因为技术原因，无法跑在路由器上，还是别的原因呢？

**Comment by IceCodeNew** [comment]
There is another project to do this job.

**Comment by qifei** [comment]
Appreciated
