### ISSUE TITLE
使用vmess+tls+websocket偶尔连接断开出下如下问题

### ISSUE THREAD

**Issue by jackhiuop** [v2fly/fhs-install-v2ray#230]
destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://baidjack.cnnn):  > dial tcp 65.45.23.64:443: operation was canceled transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://baidjack.cnnn):  > dial tcp: operation was canceled] > common/retry: all retry attempts failed

> 以上只是偶尔出现，但是就是很烦（以上ip 域名都已经处理）
`断开一会就会重新连接，求解怎么让其稳定运行，只有本人在使用`

`
{

    "log": {

        "access": "/var/log/v2ray/access.log",

        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "inbounds": [{
            "port": 3020000,
            "protocol": "vmess",
            "settings": {
                "clients": [{
                        "id": 242543b9-f3457-3-3e8-05cfd3543435434534355435434a3ff49",
                        "level": 1,
                        "alterId": 965
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "/z2455345"
                }
            }
        }
    ],
    "outbounds": [{
            "protocol": "freedom"
        }
    ]

}

`

> 以上信息还是经过了处理

**Comment by IceCodeNew** [comment]
不是安装问题发上游啊。烦。
