### ISSUE TITLE
All connection is TIME_WAIT

### ISSUE THREAD

**Issue by wishes9** [v2fly/fhs-install-v2ray#232]
Install V2ray by using your script. Below is v2ray status. When I using V2ray Client to connect my V2ray server, all connection's status are TIME_WAIT. May I know why?

v2ray.service - V2Ray Service
     Loaded: loaded (/etc/systemd/system/v2ray.service; disabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/v2ray.service.d
             └─10-donot_touch_single_conf.conf
     Active: active (running) since Wed 2022-02-16 11:01:15 CST; 6min ago
       Docs: https://www.v2fly.org/
   Main PID: 13970 (v2ray)
      Tasks: 6 (limit: 1082)
     Memory: 50.8M
     CGroup: /system.slice/v2ray.service
             └─13970 /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json

Feb 16 11:01:15 vm-ubuntu-v2ray systemd[1]: Started V2Ray Service.
Feb 16 11:01:15 vm-ubuntu-v2ray v2ray[13970]: V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)
Feb 16 11:01:15 vm-ubuntu-v2ray v2ray[13970]: A unified platform for anti-censorship.
Feb 16 11:01:15 vm-ubuntu-v2ray v2ray[13970]: 2022/02/16 03:01:15 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
Feb 16 11:01:15 vm-ubuntu-v2ray v2ray[13970]: 2022/02/16 03:01:15 [Warning] V2Ray 4.44.0 started

**Comment by IceCodeNew** [comment]
This issue has nothing to do with this project.
Open another issue on v2fly/v2ray-core.
