### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by WangZhenHao** [v2fly/fhs-install-v2ray#234]
[root@ip-172-31-15-128 /]# /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)
A unified platform for anti-censorship.
Failed to start app/proxyman/inbound: failed to listen TCP on 10086 > transport/internet: failed to listen on address: 0.0.0.0:10086 > transport/internet/tcp: failed to listen TCP on 0.0.0.0:10086 > listen tcp 0.0.0.0:10086: bind: address already in use

测试配置文件，他报这个错误，是什么意思的呢？

**Comment by IceCodeNew** [comment]
> bind: address already in use
端口占用。

如果不会解决，去 v2fly/v2ray-core 搜索 issue 区，或者 google
该问题和本项目无关
