### ISSUE TITLE
info: No new version. The current version of V2Ray is  .mktemp无法写入

### ISSUE THREAD

**Issue by xushp** [v2fly/fhs-install-v2ray#235]
https://github.com/v2fly/fhs-install-v2ray/blob/adf22292f788d003bdc8cd38e5ac2b3069f0bdab/install-release.sh#L237
这句创建的文件无法写入，导致后续比较版本出错，linux版本是ubuntu20.04
把他修改成
touch aaaa.tmp 
TMP_FILE="aaaa.tmp"就可以了

**Comment by IceCodeNew** [comment]
你应该解决 mktemp 无法写入的问题，而不是不使用 mktemp
我觉得这个工具比你自己瞎起一个文件当作临时文件要好很多
