### ISSUE TITLE
自定义安装用户

### ISSUE THREAD

**Issue by HappyLife-page** [v2fly/fhs-install-v2ray#236]
希望能添加安装时自定义用户功能，而不仅仅是默认的nobody用户，确实有这样的需求
目前的方案是手动修改启动文件用户，但比较麻烦，更新后是否又还原为默认的nobody了呢？

**Comment by IceCodeNew** [comment]
<img width="977" alt="image" src="https://user-images.githubusercontent.com/32576256/165660771-63e9c562-ff64-4146-a3eb-6c4d187dfb74.png">
你只需要 cd 到 /etc/systemd/system/v2ray@.service.d/ 目录，在当前目录下复制你能看到的文件（比如 10-donot_touch_single_conf.conf），然后在新的文件里设置用户/用户组即可。

我建议你把你的原始问题分享出来，而不是一开始就跳到「我需要自定义启动用户」这个结论上。说不定有比自定义用户更好的解决办法。
