### ISSUE TITLE
 proxy/vmess/encoding: failed to read response header > EOF

### ISSUE THREAD

**Issue by shuidaan** [v2fly/fhs-install-v2ray#239]
2022/07/03 16:01:45 [Warning] [1209104353] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > EOF
2022/07/03 16:01:45 [Warning] [1209104353] proxy/http: failed to read response from www.gstatic.com > io: read/write on closed pipe
2022/07/03 16:02:18 [Warning] [2986026721] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > EOF
2022/07/03 16:02:18 [Warning] [1011729691] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > EOF
2022/07/03 16:04:45 [Warning] [1529648546] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > EOF
2022/07/03 16:04:45 [Warning] [1529648546] proxy/http: failed to read response from www.gstatic.com > io: read/write on closed pipe

--
之前一直在用这个软件，上个月20几号出了问题，更新了一下https证书。还是连接不上。
然后更新软件info: V2Ray v4.45.2 is installed.

服务器是centos，尝试抓包，发现https端口的数据被haproxy 转发到 vmess 端口上。 但是仍旧无法代理客户端上网。

**Comment by IceCodeNew** [comment]
软件使用问题请向上游 https://github.com/v2fly/v2ray-core 反馈
