### ISSUE TITLE
连接总是超时

### ISSUE THREAD

**Issue by qualing** [v2fly/fhs-install-v2ray#242]
脚本安装后发现本地能连接到服务器，但是永远打不开网页
V2rayN可以测试延迟，而且看起来延迟并不高
![图片](https://user-images.githubusercontent.com/41828388/187529239-ee64d5e5-d0a7-42b6-bf0d-233b29b059ae.png)
但测试其他项目(TcPing, 真实延迟, 网速)就会超时
![图片](https://user-images.githubusercontent.com/41828388/187529554-6aab393e-1484-4ce1-b670-9be2043d40bd.png)
后来在网上找了找可能的原因，于是关闭了防火墙，在服务器端尝试改了时间（现在客户端和服务器使用同一个ntp服务器同步时间），并在配置文件里强制监听主IP，但都无济于事。 
附上服务器端的运行状态
![图片](https://user-images.githubusercontent.com/41828388/187533166-bc67848e-b007-496e-af0c-8df14974a511.png)
希望大家能帮忙分析一下哪里可能出了问题，谢谢！

**Comment by IceCodeNew** [comment]
使用问题去 v2fly/v2ray-core 提问，这里只处理安装问题。
