### ISSUE TITLE
v2ray 5.0问题。

### ISSUE THREAD

**Issue by loftgame** [v2fly/fhs-install-v2ray#243]
目前的安装脚本，会自动取到5.1.0的版本。。
但是运行命令
   5.0  是 /usr/local/bin/v2ray run -c /usr/local/etc/v2ray/config.json 
和4.0 的 /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json   不兼容。现在一更新就会 无法使用。

**Comment by IceCodeNew** [comment]
谢谢反馈，问题已经确认，晚上修。

**Comment by lanruo942** [comment]
遇到同样的问题，顺手更新一看 5.1.0 了。
修改启动脚本为 `run -c` 以及调整配置文件都无法启动。
已经使用命令回退到 v4. `sudo bash install-release.sh --version v4.45.0`

**Comment by IceCodeNew** [comment]
今晚忙不过来，没空改了。麻烦遇到问题的人先用上面的方法吧。
有人能提 PR 也行。

**Comment by Sanjogahara** [comment]
> 遇到同样的问题，顺手更新一看 5.1.0 了。 修改启动脚本为 `run -c` 以及调整配置文件都无法启动。 已经使用命令回退到 v4. `sudo bash install-release.sh --version v4.45.0`

你好，我是新手小白。请问出现指令：bash: install-release.sh: No such file or directory 如何处理？我的服务器本地并没有之前更新过的脚本，请问4.45版本的脚本可以从哪里获取？

**Comment by lanruo942** [comment]
> > 遇到同样的问题，顺手更新一看 5.1.0 了。 修改启动脚本为 `run -c` 以及调整配置文件都无法启动。 已经使用命令回退到 v4. `sudo bash install-release.sh --version v4.45.0`
> 
> 你好，我是新手小白。请问出现指令：bash: install-release.sh: No such file or directory 如何处理？我的服务器本地并没有之前更新过的脚本，请问4.45版本的脚本可以从哪里获取？

您好，获取脚本使用：`curl -O https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh`

**Comment by Sanjogahara** [comment]
> > > 遇到同样的问题，顺手更新一看 5.1.0 了。 修改启动脚本为 `run -c` 以及调整配置文件都无法启动。 已经使用命令回退到 v4. `sudo bash install-release.sh --version v4.45.0`
> > 
> > 
> > 你好，我是新手小白。请问出现指令：bash: install-release.sh: No such file or directory 如何处理？我的服务器本地并没有之前更新过的脚本，请问4.45版本的脚本可以从哪里获取？
> 
> 您好，获取脚本使用：`curl -O https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh`

您好，还是不行执行了两条命令，重启了v2ray还是显示仍未运行QAQ，弄了一天心碎了不知道咋办

**Comment by lanruo942** [comment]
> > > > 遇到同样的问题，顺手更新一看 5.1.0 了。 修改启动脚本为 `run -c` 以及调整配置文件都无法启动。 已经使用命令回退到 v4. `sudo bash install-release.sh --version v4.45.0`
> > > 
> > > 
> > > 你好，我是新手小白。请问出现指令：bash: install-release.sh: No such file or directory 如何处理？我的服务器本地并没有之前更新过的脚本，请问4.45版本的脚本可以从哪里获取？
> > 
> > 
> > 您好，获取脚本使用：`curl -O https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh`
> 
> 您好，还是不行执行了两条命令，重启了v2ray还是显示仍未运行QAQ，弄了一天心碎了不知道咋办

- 报错截图能否贴出来看下。
- 之前是使用什么方式安装的。
- 升级 v5 之前是否运行正常。
- 尝试回退到之前的配置文件和 service 启动脚本。

**Comment by Sanjogahara** [comment]
> > > > > 遇到同样的问题，顺手更新一看 5.1.0 了。 修改启动脚本为 `run -c` 以及调整配置文件都无法启动。 已经使用命令回退到 v4. `sudo bash install-release.sh --version v4.45.0`
> > > > 
> > > > 
> > > > 你好，我是新手小白。请问出现指令：bash: install-release.sh: No such file or directory 如何处理？我的服务器本地并没有之前更新过的脚本，请问4.45版本的脚本可以从哪里获取？
> > > 
> > > 
> > > 您好，获取脚本使用：`curl -O https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh`
> > 
> > 
> > 您好，还是不行执行了两条命令，重启了v2ray还是显示仍未运行QAQ，弄了一天心碎了不知道咋办
> 
> * 报错截图能否贴出来看下。
> * 之前是使用什么方式安装的。
> * 升级 v5 之前是否运行正常。
> * 尝试回退到之前的配置文件和 service 启动脚本。

我的操作比较怪异。之前一直是按照`bash <(curl -s -L [https://git.io/v2ray-setup.sh)`
这个指令安装的；V5之前运行是正常的。首先出了问题之后我卸载了v2ray，然后重装了一次发现还是有问题——“未在运行”。然后就依次输入您说的两行指令，退回到V4之后，重启服务之后输入v2ray status还是显示“未在运行”。

**Comment by SimonSWLiu** [comment]
我提供一个自己的解决方法，供参考：
bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
bash install-release.sh --version v4.45.0
mkdir /usr/local/etc/v2ray/
cp /etc/v2ray/config.json /usr/local/etc/v2ray/
chown -R nobody:nobody /var/log/v2ray/
这个方法每次修改配置重启前都要执行一次复制config.json
可以暂时过渡先用

期待尽快解决新版问题

**Comment by DolorHunter** [comment]
https://github.com/v2fly/fhs-install-v2ray/issues/243

**Comment by DolorHunter** [comment]
搬一些处理方法

https://github.com/v2fly/v2ray-core/issues/1956#issuecomment-1240179335

All credit to @wenge110110

**Comment by fairylyy** [comment]
sed -i 's/-config/run -config/g' /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf && systemctl daemon-reload && service v2ray restart

**Comment by azgh** [comment]
> 谢谢反馈，问题已经确认，晚上修。

@IceCodeNew 期待早日修好，好几台都不能用了，谢谢。

**Comment by Cinux-Chosan** [comment]
哎，已经是第二次被 v2ray 搞了，麻烦开发者测试好再发出来啊，第一次 alterId 的问题搞了好久才找到解决方案，第二次就是这个版本的问题，搞了一晚上要不是实在没办法了来看看 issue 可能今晚上通宵都搞不好，一度以为是配置的问题。回退到 4 版本就 OK 了

**Comment by Cinux-Chosan** [comment]
一开始想到是配置或者不兼容的问题，但是看了看文档配置好像也没问题，如果版本升级配置文档应该也会升级，而且觉得开发者也不会犯这种低级错误吧，一晚上就抱着这种对开发者信任的态度越走越远 ...

**Comment by lanruo942** [comment]
有问题大家一起解决就好。辛苦开发者以及参与讨论的大家～（送上迟到的中秋快乐🎉

**Comment by smartmaster** [comment]
solution to this issue and  working perfectluy on ubuntu 

 1. sudo vim   /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
 	add "run" in the command line
	ExecStart=/usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json
  2. sudo systemctl daemon-reload
 3. sudo systemctl restart v2ray.service
 4. sudo systemctl status v2ray.service

**Comment by wanzhiyu** [comment]
> solution to this issue and working perfectly on ubuntu
> 
>     1. sudo vim   /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
>        add "run" in the command line
>        ExecStart=/usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json
> 
>     2. sudo systemctl daemon-reload
> 
>     3. sudo systemctl restart v2ray.service
> 
>     4. sudo systemctl status v2ray.service

谢谢，不过这种方法治标不治本，您看能不能给此项目脚本提交PR哈，我看了下脚本，不太敢动

**Comment by 2821886959** [comment]
有一个方法可以在
/etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
把1第行ExecStart=
添加成
ExecStart=settings

**Comment by Zmingjun** [comment]
> 我提供一个自己的解决方法，供参考： bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh) bash install-release.sh --version v4.45.0 mkdir /usr/local/etc/v2ray/ cp /etc/v2ray/config.json /usr/local/etc/v2ray/ chown -R nobody:nobody /var/log/v2ray/ 这个方法每次修改配置重启前都要执行一次复制config.json 可以暂时过渡先用
> 
> 期待尽快解决新版问题

使用你的方法确实可以启动成功了，我觉得还是v2ray 5.0版本的问题，我是先退回4.5版本 然后再重新加载配置 然后连接成功 了

**Comment by azgh** [comment]
> 谢谢反馈，问题已经确认，晚上修。

啥时候能修上啊？

**Comment by loftgame** [comment]
> > 谢谢反馈，问题已经确认，晚上修。
> 
> 啥时候能修上啊？

安装以后 用楼上 fairylyy  的命令 执行一次。先应急。

**Comment by xbgood** [comment]
![图片](https://user-images.githubusercontent.com/98137304/193455721-ccd66071-8714-4970-a59a-2bde9cd4ca15.png)

**Comment by EricSun1993** [comment]
这个问题解决了吗

**Comment by EricSun1993** [comment]
> 

这个问题解决了吗

**Comment by wanzhiyu** [comment]
> > 
> 
> 这个问题解决了吗

解决了，你看最新的commits就知道了

**Comment by EricSun1993** [comment]
> > > 
> > 
> > 
> > 这个问题解决了吗
> 
> 解决了，你看最新的commits就知道了

版本里还没修复吧，我用脚本安装还是不行，回退到以前版本也不能正常使用

**Comment by xbgood** [comment]
> > 
> 
> 这个问题解决了吗

反正我是退回到旧版本了。先用着吧。新版本等好了再说

**Comment by Zmingjun** [comment]
> 

我用新机器 使用最新的安装脚本没问题了

**Comment by dongshimou** [comment]
2022/12/14 老版本直接`./install-release.sh` 更新还是会有这个问题。

**Comment by linzhaolover** [comment]
Ubuntu 22.04.3 LTS    v2ray 5.10
# change v2ray.service user from nobody to root
```
User=root

service v2ray restart
```
