### ISSUE TITLE
安装5.1.0启动服务出错

### ISSUE THREAD

**Issue by hanshoukai** [v2fly/fhs-install-v2ray#244]
启动服务看日志如下：
root@vultr:~# journalctl -u v2ray.service -f
Sep 07 23:00:19 vultr systemd[1]: Started V2Ray Service.
Sep 07 23:00:19 vultr v2ray[145561]: flag provided but not defined: -config
Sep 07 23:00:19 vultr v2ray[145561]: Usage of /usr/local/bin/v2ray:
Sep 07 23:00:19 vultr systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 07 23:00:19 vultr systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 07 23:00:19 vultr systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Sep 07 23:00:19 vultr systemd[1]: Stopped V2Ray Service.
Sep 07 23:00:19 vultr systemd[1]: v2ray.service: Start request repeated too quickly.
Sep 07 23:00:19 vultr systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 07 23:00:19 vultr systemd[1]: Failed to start V2Ray Service.
还请多多指教，跪谢

**Comment by hanshoukai** [comment]
详细描述：
1、用这个脚本进行安装，下载的5.1.0
2、修改配置文件如下
文件路径：/usr/local/etc/v2ray/
{
  "inbounds": [
    {
      "port": 8388, 
      "protocol": "vmess",    
      "settings": {
        "clients": [
          {
            "id": "fe4ffe28-8c41-41e0-95e2-f503b3f2a514",  
            "alterId": 0
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",  
      "settings": {}
    }
  ]
}
3、启动服务并查看输入日志
就出现如上的提示信息，没有成功启动
跪求大佬指教

**Comment by SimonSWLiu** [comment]
同样遇到 code=exited, status=2/INVALIDARGUMENT
等大佬们解决！

**Comment by StudenGit** [comment]
我也遇到了同样的问题，弄了一天了，试了各种系统都是这个错误

**Comment by StudenGit** [comment]
https://github.com/v2fly/fhs-install-v2ray/issues/243
这个，安装4.45.0吧，新版的就是有问题

**Comment by IceCodeNew** [comment]
duplicate to #243

**Comment by hanshoukai** [comment]
bash install-release.sh --version v4.45.0
