### ISSUE TITLE
v2ray.service启动失败

### ISSUE THREAD

**Issue by aba666666** [v2fly/fhs-install-v2ray#248]

**Comment by wanzhiyu** [comment]
新的V5版本的service启动路径写得有问题，默认用的是v2ray.service.d/10-donot_touch_single_conf.conf，这个里面的命令没有V5版本的run命令，导致了出错，烦死了，打算先装回老版本又不知道有没有快捷的方法

**Comment by khtah** [comment]
vim /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
把ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json  改为 ExecStart=/usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json
systemctl daemon-reload

**Comment by Yofo-me** [comment]
> vim /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf 把 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json 改为 ExecStart=/usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json systemctl daemon-reload

用不了的，同样是Ubuntu22
2023/01/06 09:14:49.271 [I] [io.go:428] Usage of /usr/local/bin/v2ray:
2023/01/06 09:14:49.271 [W] [asm_amd64.s:1571] v2ray-core: exit status 2
2023/01/06 09:14:49.460 [W] [context.go:165] PostConnection: failed to connect: unexpected exiting: check the log for more information
2023/01/06 09:14:49.460 [E] [connection.go:36] failed to connect: failed to connect: unexpected exiting: check the log for more information
2023/01/06 09:15:01.435 [I] [io.go:428] flag provided but not defined: -config
2023/01/06 09:15:01.435 [I] [io.go:428] Usage of /usr/local/bin/v2ray:
2023/01/06 09:15:01.435 [W] [asm_amd64.s:1571] v2ray-core: exit status 2
2023/01/06 09:15:01.626 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information
2023/01/06 09:15:28.651 [I] [io.go:428] flag provided but not defined: -config
2023/01/06 09:15:28.652 [I] [io.go:428] Usage of /usr/local/bin/v2ray:
2023/01/06 09:15:28.652 [W] [asm_amd64.s:1571] v2ray-core: exit status 2
2023/01/06 09:15:28.841 [W] [context.go:165] PostConnection: failed to connect: unexpected exiting: check the log for more information
2023/01/06 09:15:28.841 [E] [connection.go:36] failed to connect: failed to connect: unexpected exiting: check the log for more information
2023/01/06 09:20:08.781 [I] [io.go:428] flag provided but not defined: -config
2023/01/06 09:20:08.782 [I] [io.go:428] Usage of /usr/local/bin/v2ray:
2023/01/06 09:20:08.782 [W] [asm_amd64.s:1571] v2ray-core: exit status 2
2023/01/06 09:20:08.971 [E] [connection.go:88] failed to start v2ray-core: unexpected exiting: check the log for more information
