### ISSUE TITLE
请教v2ctl 已经不存在了吗？

### ISSUE THREAD

**Issue by nglkz** [v2fly/fhs-install-v2ray#253]
使用# bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)进行安装

操作系统为centos7 和 centos8 分别尝试
安装后v2ray 一切正常

但机器中并没有v2ctl工具
/usr/local/bin下只有v2ray文件

请教v2ctl已经不存在了吗？

**Comment by aluenkinglee** [comment]
https://github.com/v2fly/v2ray-core/issues/360 这里已经讨论过，没有必要存在了

> 使用# bash <(curl -L [https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)进行安装](https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)%E8%BF%9B%E8%A1%8C%E5%AE%89%E8%A3%85)
> 
> 操作系统为centos7 和 centos8 分别尝试 安装后v2ray 一切正常
> 
> 但机器中并没有v2ctl工具 /usr/local/bin下只有v2ray文件
> 
> 请教v2ctl已经不存在了吗？

**Comment by nglkz** [comment]
多谢指点，我研究下。
