### ISSUE TITLE
提示无网络，但是有网络

### ISSUE THREAD

**Issue by cui8** [v2fly/fhs-install-v2ray#262]
最近折腾linux系统，需要来回重装系统，但奇怪了，同样的linux系统，这次安装就出错了，求大佬解答。
我安装clash配置好代理，还是安装不成功，求大佬解答。
```
root@armbian:/opt/clash# bash install-release.sh
info: Installing V2Ray v5.2.1 for aarch64
Downloading V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v5.2.1/v2ray-linux-arm64-v8a.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 10.3M  100 10.3M    0     0  2664k      0  0:00:03  0:00:03 --:--:-- 3822k
Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v5.2.1/v2ray-linux-arm64-v8a.zip.dgst
error: Check failed! Please check your network or try again.
removed: /tmp/tmp.WuYJzESaki
```

**Comment by octopusthu** [comment]
> 最近折腾linux系统，需要来回重装系统，但奇怪了，同样的linux系统，这次安装就出错了，求大佬解答。 我安装clash配置好代理，还是安装不成功，求大佬解答。
> 
> ```
> root@armbian:/opt/clash# bash install-release.sh
> info: Installing V2Ray v5.2.1 for aarch64
> Downloading V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v5.2.1/v2ray-linux-arm64-v8a.zip
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100 10.3M  100 10.3M    0     0  2664k      0  0:00:03  0:00:03 --:--:-- 3822k
> Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v5.2.1/v2ray-linux-arm64-v8a.zip.dgst
> error: Check failed! Please check your network or try again.
> removed: /tmp/tmp.WuYJzESaki
> ```

Same here.

**Comment by cui8** [comment]
> Duplicate of #261

谢谢大佬，解决了，非常感谢

**Comment by cui8** [comment]
> > 最近折腾linux系统，需要来回重装系统，但奇怪了，同样的linux系统，这次安装就出错了，求大佬解答。 我安装clash配置好代理，还是安装不成功，求大佬解答。
> > ```
> > root@armbian:/opt/clash# bash install-release.sh
> > info: Installing V2Ray v5.2.1 for aarch64
> > Downloading V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v5.2.1/v2ray-linux-arm64-v8a.zip
> >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> >                                  Dload  Upload   Total   Spent    Left  Speed
> >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> > 100 10.3M  100 10.3M    0     0  2664k      0  0:00:03  0:00:03 --:--:-- 3822k
> > Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v5.2.1/v2ray-linux-arm64-v8a.zip.dgst
> > error: Check failed! Please check your network or try again.
> > removed: /tmp/tmp.WuYJzESaki
> > ```
> 
> Same here.

执行
```
curl -O https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
bash install-release.sh --version v5.1.0
```
安装旧版，不用修改任何东西。
