### ISSUE TITLE
無法安裝geoip.dat和geosite.dat

### ISSUE THREAD

**Issue by Nokronstella** [v2fly/fhs-install-v2ray#267]
請問這是怎麼回事?
![螢幕擷取畫面 2023-02-04 102418](https://user-images.githubusercontent.com/104825686/216741595-0b4c22ae-6f2e-4d7f-8c53-abc753853864.png)

**Comment by IceCodeNew** [comment]
> 請問這是怎麼回事? ![螢幕擷取畫面 2023-02-04 102418](https://user-images.githubusercontent.com/104825686/216741595-0b4c22ae-6f2e-4d7f-8c53-abc753853864.png)

> A TLS/SSL connect error. The SSL handshake failed. The SSL handshake can fail due to numerous different reasons so the error message may offer some additional clues. Maybe the parties could not agree to a SSL/TLS version, an agreeable cipher suite or similar.

比较有可能是你的网络被干扰了
