### ISSUE TITLE
端口每天一封，求解决办法

### ISSUE THREAD

**Issue by GinJouii** [v2fly/fhs-install-v2ray#268]
搭建好的 VLESS ，如下，使用没问题，但是每天 过了 凌晨12点以后，必封端口。
天天如此，求解决办法。有偿求 

V2ray运行状态：已安装 V2ray正在运行
 V2ray配置文件:  /etc/v2ray/config.json
 V2ray配置信息：
   协议:  VLESS
   IP(address):  45.32.x.xxx
   端口(port)：14635
   id(uuid)：xxxxxx-20c6-4397-91bb-ae51a54xxxxxx
   流控(flow)：xtls-rprx-direct
   加密(encryption)： none
   传输协议(network)： tcp
   伪装类型(type)：none
   伪装域名/主机名(host)/SNI/peer名称：www.xxxxx.click
   底层安全传输(tls)：XTLS

**Comment by IceCodeNew** [comment]
非安装问题问上游 github.com/v2fly/v2ray-core
