### ISSUE TITLE
curl: (23) Failure writing output to destination

### ISSUE THREAD

**Issue by yhongm** [v2fly/fhs-install-v2ray#279]
sudo bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                                                                                Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0bash: /dev/fd/63: No such file or directory
 23 22454   23  5164    0     0  44112      0 --:--:-- --:--:-- --:--:-- 45298
curl: (23) Failure writing output to destination

**Comment by IceCodeNew** [comment]
https://github.com/v2fly/fhs-install-v2ray/issues?q=is%3Aissue+sudo
