### ISSUE TITLE
error: Installation of unzip failed, please check your network.

### ISSUE THREAD

**Issue by farhan-adib** [v2fly/fhs-install-v2ray#282]
what should I do? :)

when I'm installing the v2ray in my server I get this error

**Comment by IceCodeNew** [comment]
> what should I do? :)
> 
> when I'm installing the v2ray in my server I get this error

Could you try to install the unzip package manually? If something goes wrong, please share the output log of the terminal.

**Comment by orionsolidified** [comment]
> what should I do? :)
> 
> when I'm installing the v2ray in my server I get this error

This is an issue with your hosting provider's ISO or the installation being corrupt. I ran into this several times with Hetzner.
