### ISSUE TITLE
The installation script fails in the Ubuntu22.04 environment

### ISSUE THREAD

**Issue by liuqimintb** [v2fly/fhs-install-v2ray#284]
When using the installation script to install V2rayCore in the Ubuntu22.04 environment, the following prompt appears:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22454  100 22454    0     0  11280      0  0:00:01  0:00:01 --:--:-- 11277
error: Failed to get release list, GitHub API response code:

**Comment by kslr** [comment]
use offline install  
https://github.com/v2fly/fhs-install-v2ray/blob/b3cbf91a19e9b4fd2637491c391a7622a3492631/install-release.sh#L186
