### ISSUE TITLE
未预期的符号 `(' 附近有语法错误

### ISSUE THREAD

**Issue by mazhonghou** [v2fly/fhs-install-v2ray#285]
[root@web ~]# sh install-release.sh 
install-release.sh:行123: 未预期的符号 `(' 附近有语法错误
install-release.sh:行123: `    elif [[ -d /run/systemd/system ]] || grep -q systemd <(ls -l /sbin/init); then'
[root@web ~]#

**Comment by mazhonghou** [comment]
find

**Comment by mazhonghou** [comment]
\(\)

**Comment by IceCodeNew** [comment]
脚本不兼容 sh
