### ISSUE TITLE
在centos7安装2ray客户端当代理使用，版本为 The current version of V2Ray is v5.10.1 .配置文文件有流控:xtls-rprx-vision无法使用！

### ISSUE THREAD

**Issue by jackyd10086** [v2fly/fhs-install-v2ray#289]
你好，配置文文件有流控:xtls-rprx-vision无法使用，能联上但出现（[root@localhost clashwenjian]# curl --socks5 127.0.0.1:7890 https://ipinfo.io
curl: (35) Encountered end of file）

 v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/v2ray.service.d
           └─10-donot_touch_single_conf.conf
   Active: active (running) since 四 2023-11-02 20:55:47 CST; 4s ago
     Docs: https://www.v2fly.org/
 Main PID: 15325 (v2ray)
   CGroup: /system.slice/v2ray.service
           └─15325 /usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json

11月 02 20:55:47 localhost.localdomain systemd[1]: Started V2Ray Service.
11月 02 20:55:47 localhost.localdomain v2ray[15325]: V2Ray 5.10.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.21.3 linux/amd64)
11月 02 20:55:47 localhost.localdomain v2ray[15325]: A unified platform for anti-censorship.
11月 02 20:55:47 localhost.localdomain v2ray[15325]: 2023/11/02 20:55:47 [Warning] V2Ray 5.10.1 started
[root@localhost clashwenjian]# curl --socks5 127.0.0.1:7890 https://ipinfo.io
curl: (35) Encountered end of file
[root@localhost clashwenjian]#

**Comment by IceCodeNew** [comment]
不解答使用问题，请咨询上游
