### ISSUE TITLE
stop_v2ray 对于首次安装逻辑处理有问题

### ISSUE THREAD

**Issue by Hill-98** [v2fly/fhs-install-v2ray#29]
首次安装的时候`systemd`并没有`v2ray`服务，这就导致了`systemctl stop v2ray`的返回代码不是`0`，导致脚本中止运行。
建议在`[[ -z "$V2RAY_CUSTOMIZE" ]]`增加一个判断条件，判断`v2ray`服务是否存在。

**Comment by dctxmei** [comment]
`stop_v2ray` 執行的前提是：

```
[[ -n "$(pgrep v2ray)" ]]
```

是否是以非 systemd 的方式運行著 V2Ray 呢？

**Comment by Hill-98** [comment]
没有，刚买的服务器，Ubuntu 18.04，安装之前我也没有检查是否有 v2ray 进程，但是我认为仅靠这个检查有点不严谨。

**Comment by dctxmei** [comment]
好吧，我需要一些時間去嘗試復現該問題。

如果你有解決方案的話，可以發一個 PR。

**Comment by dctxmei** [comment]
我沒有復現該問題，不過，我增加了一個條件判斷：

https://github.com/v2fly/fhs-install-v2ray/commit/d72aa48586d730101028fb65dff10c8f48f39733

請執行：

```
# curl -O https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/d72aa48586d730101028fb65dff10c8f48f39733/install-release.sh
```

這能否解決你所遇見的問題呢？

**Comment by Hill-98** [comment]
这个提交解决了问题

**Comment by Hill-98** [comment]
我发现我之前那个问题是如何复现的了，我把脚本名词改成了`v2ray.sh`，所以`pgrep`会匹配到，我相信不少用户也会把这个脚本改成带有`v2ray`字样的文件名，并保存到本地。
可以再进行一次修复，给`pgrep`加上`-x`，或者使用`pidof`代替。

**Comment by dctxmei** [comment]
感謝反饋，我會對此進行修復。
