### ISSUE TITLE
curl: (28) Failed to connect to github.com port 443 after 133493 ms: Couldn't connect to server

### ISSUE THREAD

**Issue by astraiosmem** [v2fly/fhs-install-v2ray#293]
os:debian 13,  

  I stuck in the downloading process, the network is stable,and I can visit github via browser, I have closed my firewall, but it doesn't work.

```
root@debian:/home/me# bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22454  100 22454    0     0  25688      0 --:--:-- --:--:-- --:--:-- 25661
info: Installing V2Ray v5.12.1 for x86_64
Downloading V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v5.12.1/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:13 --:--:--     0
**curl: (28) Failed to connect to github.com port 443 after 133493 ms: Couldn't connect to server
error: Download failed! Please check your network or try again.**
**removed: /tmp/tmp.lsQI5HWNYH**
```

I have tried the following method:
1.sudo apt update
   sudo apt install curl
2. I manually downloaded the V2Ray archive using wget successfully:
'wget https://github.com/v2fly/v2ray-core/releases/download/v5.12.1/v2ray-linux-64.zip', 
it successfully  downloaded the zip file, but I don't know how to edit the installation script to skip the downloading process
3.Use a Different Network
4. edit the /etc/hosts, I appended :
199.232.68.133 raw.githubusercontent.com
199.232.68.133 user-images.githubusercontent.com
199.232.68.133 avatars2.githubusercontent.com
199.232.68.133 avatars1.githubusercontent.com

Any assistance would be greatly appreciated.

**Comment by IceCodeNew** [comment]
> I can visit github via browser, I have closed my firewall, but it doesn't work.

Based on the information you provided, it seems like you are trying to install a V2ray client instead of a V2ray server. In this case, it's not recommended to use this project. 

If you're installing the V2ray server on machines with network connections provided by Chinese ISPs, you may want to consider an offline installation. You can do this by enabling a specific switch in the script.
