### ISSUE TITLE
URL usage?

### ISSUE THREAD

**Issue by Hhk78** [v2fly/fhs-install-v2ray#296]
```vmess://eyJhZGQiOiIxNDkuOTEuMS4xNSIsInBzIjoiVk1lc3Mgb3ZlciBXZWJTb2NrZXQiLCJzY3kiOiJhdXRvIiwidHlwZSI6IiIsInNuaSI6IiIsInBhdGgiOiIvdm1lc3Mtd3MiLCJwb3J0Ijo4MCwidiI6MiwiaG9zdCI6Ind3dy5nb29nbGUuY29tIiwidGxzIjoiIiwiaWQiOiI2YmUzZTFiMi0wNWUxLTQ2YTEtYWQzNi03MGFhYWJhYThkMTIiLCJuZXQiOiJ3cyJ9```

how can I use any vmess url? how can I convert to config file
example:

**Comment by IceCodeNew** [comment]
Please refer to https://github.com/v2fly/v2ray-core

**Comment by Hhk78** [comment]
> Please refer to https://github.com/v2fly/v2ray-core

I don't know exactly where to look.
i need a command line parameter
