### ISSUE TITLE
尝试读取let's encrypt证书时权限不足

### ISSUE THREAD

**Issue by memoz** [v2fly/fhs-install-v2ray#3]
> Jun  3 11:33:40 主机名 systemd[1]: Started V2Ray Service.
Jun  3 11:33:40 主机名 v2ray[28708]: V2Ray 4.23.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/amd64)
Jun  3 11:33:40 主机名 v2ray[28708]: A unified platform for anti-censorship.
Jun  3 11:33:41 主机名 v2ray[28708]: main: failed to read config files: [/usr/local/etc/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl:
Jun  3 11:33:41 主机名 v2ray[28708]: v2ctl> Read config:  /usr/local/etc/v2ray/config.json
Jun  3 11:33:41 主机名 v2ray[28708]: v2ray.com/core/infra/conf: Failed to build TLS config. > v2ray.com/core/infra/conf: failed to parse certificate > open /etc/letsencrypt/live/域名/fullchain.pem: permission denied > exit status 255
Jun  3 11:33:41 主机名 systemd[1]: v2ray@config.service: Main process exited, code=exited, status=23/n/a
Jun  3 11:33:41 主机名 systemd[1]: v2ray@config.service: Failed with result 'exit-code'.
Jun  3 11:33:41 主机名 systemd[1]: v2ray@config.service: Service RestartSec=100ms expired, scheduling restart.
Jun  3 11:33:41 主机名 systemd[1]: v2ray@config.service: Scheduled restart job, restart counter is at 5.
Jun  3 11:33:41 主机名 systemd[1]: Stopped V2Ray Service.

目前暂时这样解决：
> [Service]
User=root

不知道有没有更好的办法。

**Comment by unknowndev233** [comment]
> > Jun  3 11:33:40 主机名 systemd[1]: Started V2Ray Service.
> > Jun  3 11:33:40 主机名 v2ray[28708]: V2Ray 4.23.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/amd64)
> > Jun  3 11:33:40 主机名 v2ray[28708]: A unified platform for anti-censorship.
> > Jun  3 11:33:41 主机名 v2ray[28708]: main: failed to read config files: [/usr/local/etc/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl:
> > Jun  3 11:33:41 主机名 v2ray[28708]: v2ctl> Read config:  /usr/local/etc/v2ray/config.json
> > Jun  3 11:33:41 主机名 v2ray[28708]: v2ray.com/core/infra/conf: Failed to build TLS config. > v2ray.com/core/infra/conf: failed to parse certificate > open /etc/letsencrypt/live/域名/fullchain.pem: permission denied > exit status 255
> > Jun  3 11:33:41 主机名 systemd[1]: [v2ray@config.service](mailto:v2ray@config.service): Main process exited, code=exited, status=23/n/a
> > Jun  3 11:33:41 主机名 systemd[1]: [v2ray@config.service](mailto:v2ray@config.service): Failed with result 'exit-code'.
> > Jun  3 11:33:41 主机名 systemd[1]: [v2ray@config.service](mailto:v2ray@config.service): Service RestartSec=100ms expired, scheduling restart.
> > Jun  3 11:33:41 主机名 systemd[1]: [v2ray@config.service](mailto:v2ray@config.service): Scheduled restart job, restart counter is at 5.
> > Jun  3 11:33:41 主机名 systemd[1]: Stopped V2Ray Service.
> 
> 目前暂时这样解决：
> 
> > [Service]
> > User=root
> 
> 不知道有没有更好的办法。

建立一个用户，名为 readcert，然后对证书 chown root:readcert /path/to/cert && chmod 0640 path/to/cert

我之前有描述过类似方法 https://github.com/v2ray/v2ray-core/issues/2328#issuecomment-636495104

**Comment by dctxmei** [comment]
https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates
