### ISSUE TITLE
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to google.com:443 

### ISSUE THREAD

**Issue by Mstrman4** [v2fly/fhs-install-v2ray#302]
root@polite-teamn1:~# curl -x socks5h://127.0.0.1:10808 https://google.com -v
*   Trying 127.0.0.1:10808...
* Connected to 127.0.0.1 (127.0.0.1) port 10808
* SOCKS5 connect to google.com:443 (remotely resolved)
* SOCKS5 request granted.
* Connected to 127.0.0.1 (127.0.0.1) port 10808
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to google.com:443 
* Closing connection
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to google.com:443 

My config is behind cloudflare's cdn

Please help me to fix this problem❤️❤️🥹

**Comment by IceCodeNew** [comment]
You are supposed to get help at the v2fly/v2ray-core project, not here.
