### ISSUE TITLE
Debian 12 error after reboot "Special user nobody configured, this is not safe!"

### ISSUE THREAD

**Issue by sao321** [v2fly/fhs-install-v2ray#306]
如题，Debian 12重启后systemctl status v2ray查看，不停的出现
systemd[1]: [🡕] /etc/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!

**Comment by IceCodeNew** [comment]
> 如题，Debian 12重启后systemctl status v2ray查看，不停的出现 systemd[1]: [🡕] /etc/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!

这个不是一个故障，应该是警告。上游项目有关于这个问题的讨论，目前是没有人推进的状态。
简单来说，这个 service 文件是上游 v2ray/v2ray-core 项目在维护的。没办法在这里修复。
