### ISSUE TITLE
4.27.0 在arm平台安装失败

### ISSUE THREAD

**Issue by holyfight6** [v2fly/fhs-install-v2ray#33]
由于v2ray 4.27.0 arm 包名变化，现有脚本无法在arm平台正常工作了。

**Comment by IceCodeNew** [comment]
@holyfight6 请尝试 develop 分支的最新版本，回复您本地机器的 `uname -m` 结果，并告知脚本运行结果
// 如果脚本运行出错，请贴上 stdout 错误输出。

只有经过测试没有问题我才能把 develop 分支的修改 merge 进 master 分支里，这时这个错误才算真正得到修正。

**Comment by holyfight6** [comment]
@IceCodeNew 你好，我本地机器的uname -m输出为armv7l,使用develop分支的脚本可以成功安装了。
不过安装成功后服务无法正常启动，systemctl status 如下：

> ● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-08-08 12:58:28 HKT; 8min ago
  Process: 4047 ExecStart=/usr/local/bin/v2ray -confdir /usr/local/etc/v2ray/ (code=exited, status=23)
 Main PID: 4047 (code=exited, status=23)

手动允许命令/usr/local/bin/v2ray -confdir /usr/local/etc/v2ray/  结果如下：

> V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/arm)
A unified platform for anti-censorship.
2020/08/08 13:09:58 Using confdir from arg: /usr/local/etc/v2ray/
main: failed to read config files: [/usr/local/etc/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  /usr/local/etc/v2ray/config.json
v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > v2ray.com/core/infra/conf: failed to open file: geoip.dat > open /usr/local/bin/geoip.dat: no such file or directory > exit status 255

看了下dat文件已经存在于/usr/local/lib/v2ray 目录下，所以我不太清楚是安装脚本问题还是v2ray的问题。

**Comment by dctxmei** [comment]
不通過 systemd 運行的話，請在原有指令前加上：

```
$ V2RAY_LOCATION_ASSET=/usr/local/lib/v2ray/
```

**Comment by holyfight6** [comment]
@dctxmei 你好，加上变量后直接运行结果是正常的，不过systemd启动之后始终会挂：

> ● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: ena
   Active: failed (Result: exit-code) since Sat 2020-08-08 13:25:45 HKT; 2s ago
  Process: 4382 ExecStart=/usr/local/bin/v2ray -confdir /usr/local/etc/v2ray/ (co
 Main PID: 4382 (code=exited, status=23)

> Aug 08 13:25:45 raspberrypi systemd[1]: v2ray.service: Service RestartSec=100ms e
Aug 08 13:25:45 raspberrypi systemd[1]: v2ray.service: Scheduled restart job, res
Aug 08 13:25:45 raspberrypi systemd[1]: Stopped V2Ray Service.
Aug 08 13:25:45 raspberrypi systemd[1]: v2ray.service: Start request repeated too
Aug 08 13:25:45 raspberrypi systemd[1]: v2ray.service: Failed with result 'exit-c
Aug 08 13:25:45 raspberrypi systemd[1]: Failed to start V2Ray Service.

**Comment by dctxmei** [comment]
請檢查你的錯誤日誌，這可能是權限問題，該單元文件通過 nobody 用戶運行 V2Ray。

**Comment by holyfight6** [comment]
@dctxmei  查看了下日志，确实是权限问题：

> Aug 08 13:39:00 raspberrypi v2ray[4621]: V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/arm)
Aug 08 13:39:00 raspberrypi v2ray[4621]: A unified platform for anti-censorship.
Aug 08 13:39:00 raspberrypi v2ray[4621]: 2020/08/08 13:39:00 Using confdir from arg: /usr/local/etc/v2ray/
Aug 08 13:39:02 raspberrypi v2ray[4621]: 2020/08/08 13:39:02 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
Aug 08 13:39:02 raspberrypi v2ray[4621]: v2ctl> Read config:  /usr/local/etc/v2ray/config.json
Aug 08 13:39:02 raspberrypi v2ray[4621]: main: failed to create server > v2ray.com/core/app/log: failed to initialize access logger > open /var/log/v2ray/accsess.log: permission denied

多谢。
