### ISSUE TITLE
[fix] 錯誤的安裝路徑

### ISSUE THREAD

**Issue by dctxmei** [v2fly/fhs-install-v2ray#43]
geoip.dat 和 geosite.dat 原被放置在 `/usr/local/lib/v2ray/` 當中。

這實際上不符合 FHS，現已被修正為 `/usr/local/share/v2ray/`。

08-16 前受此錯誤影響的用者，請按照以下示例進行修正：

```
# mv /usr/local/lib/v2ray/ /usr/local/share/
```

```
# systemctl edit --full v2ray.service

Environment=V2RAY_LOCATION_ASSET=/usr/local/share/v2ray/
```

```
# systemctl edit --full v2ray@.service

Environment=V2RAY_LOCATION_ASSET=/usr/local/share/v2ray/
```

**Comment by sheldonldev** [comment]
A tip when the installation is done:

" installed: /usr/local/etc/v2rayconfig.json " should be " installed: /usr/local/etc/v2ray/config.json "

**Comment by IceCodeNew** [comment]
We are already working on this. Refer to #126.
And please, don't necro closed issue like this, at least not without posting a new standalone issue.
This issue was closed and pinned because it is for people who are migrating from an old installation. It has nothing to do with your feedback.
