### ISSUE TITLE
v4.27.0 无法搭配最新的install-dat-release.sh

### ISSUE THREAD

**Issue by zhaoguomanong** [v2fly/fhs-install-v2ray#44]
运行v2ray 提示找不到geoip.dat, geosite.dat
麻烦尽快修复．需要发布新版本的v2ray-core?? 还是已经有了新版本，脚本检测的版本号错了？
大致问题原因：v4.27.0 二进制文件里面引用的geo 路径为旧的路径不是最新的
/usr/local/share/v2ray
我现在用的install-dat-release.sh安装v2ray跑不起来，程序报错，应该需要搭配更新版本的v2ray版本

**Comment by zhaoguomanong** [comment]
已知问题，我看到说８月１６号之前会出现该问题，意思是8.16会发布新的core来修复该路径错误的问题？

**Comment by zhaoguomanong** [comment]
我临时把json配置里面引用到geo的规则删除后，暂时能跑起来，等待发布新版本解决问题

**Comment by dctxmei** [comment]
請依據 issue #43 進行修正。

**Comment by dctxmei** [comment]
請依據 issue #43 進行修正。

**Comment by zhaoguomanong** [comment]
> 請依據 issue #43 進行修正。

如果之前老版本的执行过go.sh --remove /usr/local/lib/v2ray/ 这个目录就删除了，我就是先用旧的go.sh进行删除之后彻底重装的．

如果用了老版本脚本执行删除操作，或者是新用户第一次装v2ray, #43 里面的方法就无效了．

**Comment by dctxmei** [comment]
issue #43 針對的是 pull #42 之前執行過腳本的用者。

在 pull #42 之後從舊腳本遷移至此的，可無視 issue #43；
在 pull #42 之後通過此腳本進行首次安裝的，亦可無視 issue #43。

**Comment by zhaoguomanong** [comment]
就是首次安装有问题，v2ray 日志提示找不到geo文件。
建议同步发布新版本的core。保证不影响用户使用。

**Comment by dctxmei** [comment]
你沒有通過 systemd 管理 V2Ray 麼？

**Comment by zhaoguomanong** [comment]
> 你沒有通過 systemd 管理 V2Ray 麼？

没有，我禁用了systemd ，我是自己写的脚本，全路径启动运行的。

**Comment by dctxmei** [comment]
不通過 systemd 進行管理的話，請在原有指令前加上 `V2RAY_LOCATION_ASSET=/usr/local/share/v2ray/`。

**Comment by zhaoguomanong** [comment]
> 不通過 systemd 進行管理的話，請在原有指令前加上 `V2RAY_LOCATION_ASSET=/usr/local/share/v2ray/`。

添加export V2RAY_LOCATION_ASSET="/usr/local/share/v2ray/"
问题解决．

建议把这条写到wiki

谢谢
