### ISSUE TITLE
建议该项目使用简体字

### ISSUE THREAD

**Issue by rprx** [v2fly/fhs-install-v2ray#47]
目前旧脚本已被弃用，该项目成为唯一的官方脚本。考虑到 V2Ray 主要使用群体的文化背景，简体字与相关词（如：软体->软件）更亲和且更易于阅读和理解、更易于视觉上的感知（如对于简体字用户，“使用证书时权限不足”比“使用證書時權限不足”更醒目）。

**Comment by IceCodeNew** [comment]
先给 README 做了到简体中文的转换，接下来会检查 Wiki 那边是否也需要转换。

**Comment by rprx** [comment]
> 
> 
> 先给 README 做了到简体中文的转换，接下来会检查 Wiki 那边是否也需要转换。

似乎将简体中文设为默认更好，同时提供繁体中文及英文入口。

**Comment by IceCodeNew** [comment]
> > 先给 README 做了到简体中文的转换，接下来会检查 Wiki 那边是否也需要转换。
> 
> 似乎将简体中文设为默认更好，同时提供繁体中文及英文入口。

这个是我的私心，我尊重最开始建立这个项目的用户，他习惯用繁体中文写作，我就继续保留繁体中文为默认。
简体中文的跳转链接已经放在最开头了，我觉得没什么不方便的。
欢迎贡献英文翻译。

**Comment by IceCodeNew** [comment]
Wiki 的多语言支持也做好了。

**Comment by IceCodeNew** [comment]
@dctxmei Wiki 页我做了侧边栏，增强了给用户导航的能力。不过具体分类是否合理，以及以繁体中文书写的大类名称，这些都想麻烦您看一眼，有必要的话帮我做些修改完善，谢谢。

**Comment by rprx** [comment]
> 
> 
> Wiki 的多语言支持也做好了。

感谢贡献，请把 wiki 页右侧的旗子替换为其它标识符。。。不想涉及政治问题

**Comment by rprx** [comment]
应该使用 zh-Hans 表示简体中文，zh-Hant 表示繁体中文。

**Comment by IceCodeNew** [comment]
![image](https://user-images.githubusercontent.com/32576256/90335536-39a9a200-e008-11ea-9d80-c4c8601bf618.png)
zh-CN 这样的表示也属于 ISO 标准定义过的代码标记里的一种，ISO 并未认定台湾是一个国家，所以使用这样的表记在我看来是没有问题的。

还有我觉得避免政治问题最好的办法是把简体中文的版本删了只留下繁体中文一种，不然两种版本对比起来都让人觉得不爽。中国只用简体中文，这个项目里又有繁体中文又有简体中文算怎么一回事呢？
而你使用简体中文给别人写翻墙软件的 FAQ 或者教程，恐怕又是非常严重的政治问题了。

**Comment by IceCodeNew** [comment]
论简体有大陆简体有新加坡简体，论繁体有香港繁体澳门繁体台湾正体，我觉得硬把 zh-CN 改成 zh-Hans 是一种退步。

**Comment by rprx** [comment]
关于旗子：请勿回避这个问题，**建议先打开 F12 看一下**。我的立场很明确，不可以这样使用旗子，会招惹不必要的麻烦。

关于 zh-CN 还是 zh-Hans：这不是大问题，但从全人类的角度来看，zh-Hans 比 zh-CN 更通用。重申：这不是重点。

> 而你使用简体中文给别人写翻墙软件的 FAQ 或者教程，恐怕又是非常严重的政治问题了。

抬杠。

**Comment by rprx** [comment]
提醒：当这个项目从“备选的”升级为“唯一的”且官方推荐时，项目发展应当是有更多考虑且更广泛适用的，情况已经不一样了。

**Comment by IceCodeNew** [comment]
> 关于旗子：请勿回避这个问题，**建议先打开 F12 看一下**。我的立场很明确，不可以这样使用旗子，会招惹不必要的麻烦。

我这怎么突然天降一个帽子下来，我对你的提议并没有多大兴趣所以并没有把每个字都读进去，可以理解了吗？
你如果觉得这个旗帜不合适，自己去改呗，我实在是没兴趣。我在解决你的这个 Issue 时才第一次接触到给 Wiki 加多语言支持这块，ArchiSteamFarm 给我做了一个很好的榜样，它那边怎么做的，我这边就照着怎么做。
所以我从一开始就没有的意思，有人突然要提醒我说你做的事可以被怎么怎么解读，我也会当成有人在抬杠，而且没有兴趣一路奉陪到底。

说到底您开发翻墙软件，还觉得自己可以把这件事做的又红又专吗？你的立场确实很明确，那你为啥有时间等我和你扯皮完再去改，而不是自己赶紧去改呢？

**Comment by rprx** [comment]
首先，现在我并没有对这个项目的写权限，其次，我的第一句话是这样的：

> 感谢贡献，请把 wiki 页右侧的旗子替换为其它标识符。。。不想涉及政治问题

**并没有解读你的意思，作为 v2ray 的贡献者，我只是不希望 v2ray 陷入政治争端，给项目及贡献者们带来不必要的麻烦。**

> 说到底您开发翻墙软件，还觉得自己可以把这件事做的又红又专吗？

这就是你在解读我的意思了，在你看来这个世界是非黑即白的吗？还有，请学会就事论事，谢谢。

**Comment by rprx** [comment]
> 所以我从一开始就没有的意思，有人突然要提醒我说你做的事可以被怎么怎么解读，我也会当成有人在抬杠，而且没有兴趣一路奉陪到底。

如果在你看来我那句话是这样的提醒，那么我没理解错的话，是你把提醒当成了抬杠。

**Comment by IceCodeNew** [comment]
你要是在这里一开始的说法和群里面讲的一样简洁，我早就还在电脑旁边的时候就改了。
你看群里面一来一回两条消息就聊完的事，在这边扯了多久。

**Comment by IceCodeNew** [comment]
给吃瓜用户看一下群里的沟通过程（这个 Issue 里面全程都没有聊到一个频道

朋友们，清晰的沟通真的很重要啊（

![image](https://user-images.githubusercontent.com/32576256/90337520-9c556a80-e015-11ea-896c-783a89cf9e9d.png)

![image](https://user-images.githubusercontent.com/32576256/90337531-a8d9c300-e015-11ea-908c-b96d53478b15.png)

![image](https://user-images.githubusercontent.com/32576256/90337537-af683a80-e015-11ea-9f3d-ca0a429dd227.png)

**Comment by IceCodeNew** [comment]
@rprx 昨天只删了繁中版侧边栏的国旗，漏了简中版，我今天一并补上了。
另外因为我违反了一些其他开发者约定俗成的社交规矩，所以我没有机会看到群里的最终投票结果，最后我还是按照我最心仪的一种语言代码来修改了（`zh-CN` -> `zh-Hans-CN`）
