### ISSUE TITLE
flags are not languages

### ISSUE THREAD

**Issue by DuckSoft** [v2fly/fhs-install-v2ray#52]
Do not use flags for languages in project wiki.

http://www.flagsarenotlanguages.com/

![图片](https://user-images.githubusercontent.com/7822648/90336958-c6a52900-e011-11ea-96b8-5e9c96e930ea.png)

**Comment by IceCodeNew** [comment]
明天起床删，现在几点了。

**Comment by IceCodeNew** [comment]
Duplicate to #47

**Comment by IceCodeNew** [comment]
@rprx 昨天只删了繁中版侧边栏的国旗，漏了简中版，我今天一并补上了。
另外因为我违反了一些其他开发者约定俗成的社交规矩，所以我没有机会看到群里的最终投票结果，最后我还是按照我最心仪的一种语言代码来修改了（`zh-CN` -> `zh-Hans-CN`）
