### ISSUE TITLE
[Todo] 从 Release 中获得 Systemd 文件，而不从网络下载

### ISSUE THREAD

**Issue by kslr** [v2fly/fhs-install-v2ray#53]
https://github.com/v2fly/fhs-install-v2ray/blob/ddaea17fbb5c2b206f998986be69c2f2d19eab63/install-release.sh#L384-L400

**Comment by kslr** [comment]
另外，我刚刚彻底移除了 systemv

**Comment by IceCodeNew** [comment]
这个提议我觉得很好，不过看 @dctxmei 已经在着手了？
我的建议是趁此机会把 `.service` 文件里一些写死的地方改成用变量填充，这方面我觉得 HAProxy 的 systemd 配置非常值得参考
