### ISSUE TITLE
error: Only Linux distributions using systemd are supported.

### ISSUE THREAD

**Issue by niphor** [v2fly/fhs-install-v2ray#54]
Ubuntu 14.04.6 LTS

旧系统 没systemd装不了

旧的go.sh 也被更新了，打印的迁移文档上也没注明，跟着步骤 删了二进制文件，现在只能手动去复制还原...

**Comment by IceCodeNew** [comment]
Ubuntu 14.04 已经抵达了生命的终点，继续使用它是不明智的。
如果你不愿意或者因为某些缘故不能升级操作系统，那确实你有非使用旧安装脚本不可的理由——但就像我在置顶 Issue 里提到的那样，旧安装脚本在 v2ray-core 改变发布版本的文件命名方式以后已经不能使用，欢迎你 PR 把那个脚本修好。
二选一吧。

**Comment by niphor** [comment]
用不用14.04是其次的，主要是：
`迁移指南`的WIKI 起码标注一下*不支持非Systemd的系统*
毕竟 `https://install.direct/go.sh` 的脚本没这个限制,按着流程走很难注意到这个*breaking change*。
而且这个*breaking change*就只有 readme 标题下面有句英文提及，还是个引用段落，更加不明显。

**Comment by IceCodeNew** [comment]
> @IceCodeNew 
> 用不用14.04是其次的，主要是：
> `迁移指南`的WIKI 起码标注一下*不支持非Systemd的系统*
> 毕竟 `https://install.direct/go.sh` 的脚本没这个限制,按着流程走很难注意到这个*breaking change*。
> 而且这个*breaking change*就只有 readme 标题下面有句英文提及，还是个引用段落，更加不明显。

这个提议不错，你可以考虑去给文档加上这段提示。发 PR，我会合并。
BTW 执行任何脚本之前，你都应该先检查脚本，了解它会干什么事——不管它是不是官方脚本。
