### ISSUE TITLE
提出默认使用单配置而不是多配置

### ISSUE THREAD

**Issue by kslr** [v2fly/fhs-install-v2ray#57]
优点

降低复杂度
和以往行为保持一致

缺点
使用多配置要使用命令参数来生成

**Comment by phlinhng** [comment]
我认为没必要改，多配置文件的行为是读取 confdir 内的所有文件后拼接起来，按理来说是兼容单配置的。在我的服务器上以 confdir 参数启用单配置模式没有任何问题，如果有个别用户启动不起来，应该修复 v2ray-core 的 bug 而不是脚本。

**Comment by kslr** [comment]
> 我认为没必要改，多配置文件的行为是读取 confdir 内的所有文件后拼接起来，按理来说是兼容单配置的。在我的服务器上以 confdir 参数启用单配置模式没有任何问题，如果有个别用户启动不起来，应该修复 v2ray-core 的 bug 而不是脚本。

是兼容的，作为一种快速兼容的办法就是多配置下放单文件，但考虑到可能 config_node1 config_node2 的存在，单文件更合适

> 如果有个别用户启动不起来 这个要单独谈

这里的目标是为了减少迁移工作

**Comment by kslr** [comment]
@dctxmei @nicholascw

**Comment by phlinhng** [comment]
> > 我认为没必要改，多配置文件的行为是读取 confdir 内的所有文件后拼接起来，按理来说是兼容单配置的。在我的服务器上以 confdir 参数启用单配置模式没有任何问题，如果有个别用户启动不起来，应该修复 v2ray-core 的 bug 而不是脚本。
> 
> 是兼容的，作为一种快速兼容的办法就是多配置下放单文件，但考虑到可能 config_node1 config_node2 的存在，单文件更合适
> 
> 如果有个别用户启动不起来 这个要单独谈
> 
> 这里的目标是为了减少迁移工作

有道理，我现在想站队单配置文件了。有多配置文件需求的人应该懂得怎么俢改 systemd。

**Comment by nicholascw** [comment]
> 我认为没必要改，多配置文件的行为是读取 confdir 内的所有文件后拼接起来，按理来说是兼容单配置的。在我的服务器上以 confdir 参数启用单配置模式没有任何问题，如果有个别用户启动不起来，应该修复 v2ray-core 的 bug 而不是脚本。

没道理兼容以前的默认行为啊，我日常丢一堆inactive的配置在/etc/v2ray， 直接应用所有的显然不合理。。更何况以前的脚本默认行为还是把模板统统丢进 /etc/v2ray。。

我坚定 **`v2ray.service` 里面用 `-config`, `v2ray@.service` 用 `-confdir`** 的立场~一百年不动摇~ 不仅兼容原来脚本的行为，而且反正 `v2ray@.service` 要用户显式启用，应该是知道用法，且在 /etc/v2ray 下面建子目录用于多个实例的做法也非常易于维护。。更完善一点的做法是类似fontconfig，提供 `/etc/v2ray/conf.avail` 和 `/etc/v2ray/conf.d`, 让用户把要启用的文件夹软链接进`conf.d` 。
