### ISSUE TITLE
非 root 用户使用 sudo 运行时报错

### ISSUE THREAD

**Issue by phlinhng** [v2fly/fhs-install-v2ray#6]
`sudo bash <(curl -sL https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)` 会报 `bash: /dev/fd/63: No such file or directory` 这个错，造成无法顺利安装

**Comment by tzwjkl** [comment]
`sudo su`或者`sudo -i`进入root用户再执行完整命令就行了，或者把脚本保存到本地之后`sudo ./sh`？

**Comment by phlinhng** [comment]
这样是治标不治本的，旧的 go.sh 脚本没有这个问题。

**Comment by tzwjkl** [comment]
> 这样是治标不治本的。旧的 go.sh 脚本没有这个问题。

你确定旧的go.sh没有吗？我以前还不知道sudo -i的时候是遇到过的。

**Comment by tzwjkl** [comment]
[另外你也可以这样做](https://github.com/233boy/v2ray/issues/181#issuecomment-485095408)

**Comment by phlinhng** [comment]
> 你确定旧的go.sh没有吗？我以前还不知道sudo -i的时候是遇到过的。

@tzwjkl 是我記錯了， 我以前運行  go.sh 用的指令是 `curl -sL ttps://install.direct/go.sh | sudo bash`，完全像在 root 底下運行一樣，沒遇到問題。    
同理， install-realese.sh 應該也可以改用 `curl -sL https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh |  bash` 解決。
