### ISSUE TITLE
脚本怎么用啊，能给个方法吗？

### ISSUE THREAD

**Issue by 1265578519** [v2fly/fhs-install-v2ray#61]
bash <(curl -L -s https://install.direct/go.sh)

官网这个安装现在不了，从里面的url看到这个项目了

**Comment by IceCodeNew** [comment]
@1265578519 https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this-zh-Hans-CN

**Comment by IceCodeNew** [comment]
https://www.v2fly.org/chapter_00/install.html#linux-%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC

**Comment by 1265578519** [comment]
@IceCodeNew 谢谢，我花点时间研究下它，这改动太糟糕了

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/90524503-b8394780-e1a0-11ea-801a-32cb28c1ebbc.png)

应该是这个，我尝试下
bash <(curl https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)

**Comment by 1265578519** [comment]
@IceCodeNew  /etc/v2ray/config.json 我安装后找不到配置文件，你能帮帮我吗？/usr/local/etc/ 目录下也是空的
![image](https://user-images.githubusercontent.com/6442439/90524850-241bb000-e1a1-11ea-93c3-e712a44d119c.png)

**Comment by IceCodeNew** [comment]
不要把 issue 当成聊天一样的用，还有贴错误日志的时候用 ` ``` ` 比截图更加友好。

遇到问题先
`journalctl --boot -u v2ray`
`V2RAY_LOCATION_ASSET=/usr/local/share/v2ray/ v2ray -test -confdir /usr/local/etc/v2ray/`
`ls -alF --color=auto /usr/local/etc/v2ray`
三连，把输出用 ` ``` ` 包裹起来发上来。

**Comment by 1265578519** [comment]
我卸载重装了它，还是没找到配置文件无法使用
`[root@VM-0-16-centos ~]# journalctl --boot -u v2ray
-- Logs begin at Tue 2020-08-18 21:37:28 CST, end at Tue 2020-08-18 22:28:20 CST. --
Aug 18 22:12:12 VM-0-16-centos systemd[1]: Started V2Ray Service.
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/amd64)
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: A unified platform for anti-censorship.
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: 2020/08/18 22:12:12 Using confdir from arg: /usr/local/etc/v2ray/
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: 2020/08/18 22:12:12 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: v2ctl> Read config:  /usr/local/etc/v2ray/00_log.json
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: v2ctl> Read config:  /usr/local/etc/v2ray/01_api.json
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: v2ctl> Read config:  /usr/local/etc/v2ray/02_dns.json
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: v2ctl> Read config:  /usr/local/etc/v2ray/03_routing.json
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: v2ctl> Read config:  /usr/local/etc/v2ray/04_policy.json
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: v2ctl> Read config:  /usr/local/etc/v2ray/05_inbounds.json
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: v2ctl> Read config:  /usr/local/etc/v2ray/06_outbounds.json
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: v2ctl> Read config:  /usr/local/etc/v2ray/07_transport.json
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: v2ctl> Read config:  /usr/local/etc/v2ray/08_stats.json
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: v2ctl> Read config:  /usr/local/etc/v2ray/09_reverse.json
Aug 18 22:12:12 VM-0-16-centos v2ray[4317]: 2020/08/18 22:12:12 [Warning] v2ray.com/core: V2Ray 4.27.0 started
Aug 18 22:26:21 VM-0-16-centos systemd[1]: Stopping V2Ray Service...
Aug 18 22:26:21 VM-0-16-centos systemd[1]: Stopped V2Ray Service.
[root@VM-0-16-centos ~]# V2RAY_LOCATION_ASSET=/usr/local/share/v2ray/ v2ray -test -confdir /usr/local/etc/v2ray/
V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/amd64)
A unified platform for anti-censorship.
2020/08/18 22:28:21 Using confdir from arg: /usr/local/etc/v2ray/
Configuration OK.
[root@VM-0-16-centos ~]# ls -alF --color=auto /usr/local/etc/v2ray
total 48
drwxr-xr-x  2 root root 4096 Aug 18 22:09 ./
drwxr-xr-x. 3 root root 4096 Aug 18 22:09 ../
-rw-r--r--  1 root root    3 Aug 18 22:09 00_log.json
-rw-r--r--  1 root root    3 Aug 18 22:09 01_api.json
-rw-r--r--  1 root root    3 Aug 18 22:09 02_dns.json
-rw-r--r--  1 root root    3 Aug 18 22:09 03_routing.json
-rw-r--r--  1 root root    3 Aug 18 22:09 04_policy.json
-rw-r--r--  1 root root    3 Aug 18 22:09 05_inbounds.json
-rw-r--r--  1 root root    3 Aug 18 22:09 06_outbounds.json
-rw-r--r--  1 root root    3 Aug 18 22:09 07_transport.json
-rw-r--r--  1 root root    3 Aug 18 22:09 08_stats.json
-rw-r--r--  1 root root    3 Aug 18 22:09 09_reverse.json
[root@VM-0-16-centos ~]# `

**Comment by 1265578519** [comment]
bash <(curl -L -s http://mg.cd-sw.com/v2/go.sh)
群里一位朋友给了我新的v2ray安装url，我成功安装了，已经可以正常连接并使用4.27最新版本，如果你能帮助我解决配置文件问题的话，希望你能回复一下

···
[root@VM-0-16-centos ~]# bash <(curl -L -s http://mg.cd-sw.com/v2/go.sh)
Installing V2Ray v4.27.0 on x86_64
Downloading V2Ray: http://mg.cd-sw.com/v2/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.2M  100 12.2M    0     0  2541k      0  0:00:04  0:00:04 --:--:-- 3045k
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /usr/bin/v2ray/geoip.dat  
  inflating: /usr/bin/v2ray/geosite.dat  
  inflating: /usr/bin/v2ray/v2ctl    
  inflating: /usr/bin/v2ray/v2ray    
PORT:21668
UUID:2c51f283-a1d9-4d13-93a5-dd3a2c3101b7
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /etc/systemd/system/v2ray.service  
V2Ray v4.27.0 is installed.
[root@VM-0-16-centos ~]# 
···

**Comment by IceCodeNew** [comment]
> [root@VM-0-16-centos ~]# ls -alF --color=auto /usr/local/etc/v2ray
> total 48
> drwxr-xr-x  2 root root 4096 Aug 18 22:09 ./
> drwxr-xr-x. 3 root root 4096 Aug 18 22:09 ../
> -rw-r--r--  1 root root    3 Aug 18 22:09 00_log.json
> -rw-r--r--  1 root root    3 Aug 18 22:09 01_api.json
> -rw-r--r--  1 root root    3 Aug 18 22:09 02_dns.json
> -rw-r--r--  1 root root    3 Aug 18 22:09 03_routing.json
> -rw-r--r--  1 root root    3 Aug 18 22:09 04_policy.json
> -rw-r--r--  1 root root    3 Aug 18 22:09 05_inbounds.json
> -rw-r--r--  1 root root    3 Aug 18 22:09 06_outbounds.json
> -rw-r--r--  1 root root    3 Aug 18 22:09 07_transport.json
> -rw-r--r--  1 root root    3 Aug 18 22:09 08_stats.json
> -rw-r--r--  1 root root    3 Aug 18 22:09 09_reverse.json
> [root@VM-0-16-centos ~]# 
> ```

你说你刚刚卸载重装？可是这输出明显不对劲。
安装脚本已经更新，你新执行安装脚本的时候只会安装单配置文件了。

**Comment by IceCodeNew** [comment]
> 你能帮助我解决配置文件问题的话，希望你能回复一下

配置文件的问题你不应该在这个地方问，这里只管你遇到的安装脚本使用问题。
请转到 v2fly/v2ray-core 提 issue 表述你在配置文件上遇到的问题，并提请您注意遵守问题模板。

**Comment by 1265578519** [comment]
是，我使用--remove卸载了，重新再次运行了安装命令，还是没有出现配置文件，我购买的服务器是centos 7.6.1810的操作系统

**Comment by IceCodeNew** [comment]
fhs-install-v2ray 从一开始创建的配置文件就是空的，不会像现在已经被废除的旧安装脚本那样为用户创建一套开箱即用的配置。
我认为 v2ray 这样的项目确实也没有默认配置可言，请用户不要再将这件事作为 bug 提交上来，你们既然选择自建，就应该自己写自己的配置了。
过程中遇到任何问题，请参阅 v2fly.org。

**Comment by 1265578519** [comment]
@IceCodeNew 配置文件需要写在哪里路径呢？文档中都没有任何说明，配置文件肯定会写，问题写在哪才能让它生效？如何加载配置文件？

**Comment by IceCodeNew** [comment]
> @IceCodeNew 配置文件需要写在哪里路径呢？文档中都没有任何说明，配置文件肯定会写，问题写在哪才能让它生效？如何加载配置文件？

有空请多阅读下《提问的智慧》。
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

你的第一、第二个句子语序都有问题，我看不出你到底想说什么。

> 如何加载配置文件？

v2ray.service 会负责启动程序并加载配置文件。

**Comment by 1265578519** [comment]
@IceCodeNew 我看完了提问的智慧，求你了，你能告诉我配置文件应该放在哪吗？

**Comment by IceCodeNew** [comment]
> @IceCodeNew 我看完了提问的智慧，求你了，你能告诉我配置文件应该放在哪吗？

你遇到的问题是配置文件为空，然后我在 https://github.com/v2fly/fhs-install-v2ray/issues/61#issuecomment-675525711 这里回复告知你这个默认产生的配置文件本来就是空的。
那现在解决问题的思路不就是自己把这个空的配置文件填充上内容吗？你直接编辑 `/usr/local/etc/v2ray/config.json` 不就完了。
你说你看完了提问的智慧，那请问你的功课做在哪儿了？
> 低声下气不能代替你的功课
> 去掉无意义的提问句
>> 一般来说，避免用 是或否、对或错、有或没有类型的问句，除非你想得到是或否类型的回答。

RTFM

**Comment by 1265578519** [comment]
终于解决了，感谢群里朋友的帮助，提供了配置文件路径在/usr/local/etc/v2ray/config.json 该出文档中并没有任何说明，之前我尝试/etc/v2ray/config.json 也不生效，/usr/local/etc/ 目录下也不存在
官方人员说config.json=00_log.json 让我把自己写的config.json配置文件信息重命名成00_log.json 我试了还是不行
现在用/usr/local/etc/v2ray/config.json 终于成功能用了
![image](https://user-images.githubusercontent.com/6442439/90534201-09026d80-e1ac-11ea-9d1b-fc6e6bb90e55.png)

感谢群里这位朋友的帮助
![image](https://user-images.githubusercontent.com/6442439/90534254-1a4b7a00-e1ac-11ea-91af-ce7db02e5f39.png)

**Comment by xqzr** [comment]
解决就好
