### ISSUE TITLE
修改配置文件路径后，启动脚本中的配置文件路径仍为/usr/local/etc/v2ray

### ISSUE THREAD

**Issue by hspmanbu** [v2fly/fhs-install-v2ray#62]
为了配置方便我将配置路径改回了/etc/v2ray，但是启动的时候却无反应，查了一下状态才知道/etc/systemd/system下启动脚本里的配置文件路径并未随之改变，仍为/usr/local/etc/v2ray。
希望可以完善一下
![微信截图_20200818220148](https://user-images.githubusercontent.com/20383371/90522795-ba020b80-e19e-11ea-96f4-63acfc9af8b2.png)

**Comment by IceCodeNew** [comment]
是这样的，安装脚本目前的文件结构都是写死的。用户如果自定义了这些路径，在目前来说会被当做高级用户，需要自己调整启动脚本来配合自己做的修改。
请期待上游 v2fly/v2ray-core 对 v2ray.service 文件的进一步改进，或亲自参与到项目中来贡献。
