### ISSUE TITLE
对于FHS的链接引用不准确的问题

### ISSUE THREAD

**Issue by marillindie** [v2fly/fhs-install-v2ray#67]
目前, 对FHS描述引用的链接是:
https://wiki.linuxfoundation.org/lsb/fhs
该链接意在解释FHS标准, 然而页面中却并没有详细解释, 反而有过多的链接 (其中只有一个链接可以解决问题).
个人认为这一链接过于宽泛, 不能直接解决问题, 应更换为:
https://refspecs.linuxfoundation.org/fhs.shtml

**Comment by inmaldrerah-e** [comment]
> > 很多人只是想知道fhs是什么
> 
> 同意，我觉得没有必要修改

恰恰相反, 我觉得正因为很多人想知道fhs是什么才要修改

**Comment by kslr** [comment]
那么需要的人寻找文档是很合理的，不需要的人看简介就够了。
而不是任何人都要下载一份pdf文件。

**Comment by d4rkblue** [comment]
要不考虑两个链接都放上去，一个是简介版，一个是解释版。

**Comment by DuckSoft** [comment]
何须那么麻烦，直接 link 到 Wikipedia。
