### ISSUE TITLE
/usr/local/lib/v2ray 不存在

### ISSUE THREAD

**Issue by phlinhng** [v2fly/fhs-install-v2ray#7]
在某些情况下，似乎不会建立这个目录，也不会放入 geoip.dat 和  geosite.dat，造成 v2ray 启动出错。

**Comment by dctxmei** [comment]
請提供更詳盡的信息，以用於處理錯誤。

**Comment by phlinhng** [comment]
我是一键脚本作者，这个问题是用我脚本的人回报给我的，我自已也复现不出来。仅回报一下，让你们留 意。
