### ISSUE TITLE
易用性太差

### ISSUE THREAD

**Issue by zenmaster-cd** [v2fly/fhs-install-v2ray#70]
换脚本不说，里面config文件空的，我还自己写 你升级了什么？你这是在破解使用体验 作为普通用来说太麻烦了 并没有原脚本易用

**Comment by zenmaster-cd** [comment]
关什么

**Comment by zenmaster-cd** [comment]
说不得了？

**Comment by kslr** [comment]
抱怨是在浪费所有人的时间和精力，作为一个社区化的项目，你可以参与改进或者讨论合理性，而不是单纯发泄一通，这是在浪费大家的时间。

时间宝贵，还是做一些有意义的事情吧

**Comment by zenmaster-cd** [comment]
牛逼牛逼

**Comment by zenmaster-cd** [comment]
真的是，该你拽

**Comment by kslr** [comment]
希望你可以学会如何好好说话，以及如何尊重别人。

Q 为什么移除之前的脚本？
A 因为功能失效无人维护以及域名即将过期

**Comment by zenmaster-cd** [comment]
作为脚本，你要保证易用啊，用户使用应该更方便，而不是更麻烦。信息不对称，导致我并不知道脚本域名过期，且网站并没有声明。来就把问题关了，什么意思？你觉得你很尊重人？如果你写出来只是拿给程序人员使用，我觉没问题。当我没说这个问题，但如果不是，你是不是因该考虑使用的便捷性？或者让使用者更好的过度？

**Comment by zenmaster-cd** [comment]
你也不用回了，怕浪费您时间了 毕竟你时间宝贵

**Comment by kslr** [comment]
这个脚本在官网和频道已经提前公示了6个月了。readne 上有写迁移指南，现在和之前的比只有路径变化。

**Comment by kslr** [comment]
> 你也不用回了，怕浪费您时间了 毕竟您时间宝贵

不必如此，你愿意沟通我也愿意和你沟通

**Comment by zenmaster-cd** [comment]
https://www.v2ray.com/ 明显位置并未找到  我也不想扯了 毕竟只是普通用户，不会时时刻刻，去看官网 看代码，我只能说，不合适我，我要求太多了。 用户体验对我来说比较重要。

**Comment by kslr** [comment]
> https://www.v2ray.com/ 明显位置并未找到 我也不想扯了 毕竟只是普通用户，不会时时刻刻，去看官网 看代码，我只能说，不合适我，我要求太多了。 用户体验对我来说比较重要。

https://www.v2fly.org/

**Comment by DuckSoft** [comment]
> https://www.v2ray.com/ 明显位置并未找到 我也不想扯了 毕竟只是普通用户，不会时时刻刻，去看官网 看代码，我只能说，不合适我，我要求太多了。 用户体验对我来说比较重要。

v2ray.com 早已停止维护。找不到很正常。

**Comment by zenmaster-cd** [comment]
我对我说“我还自己写 你升级了什么？”道歉对不起 伤害你心灵了，但对于易用性观点我拒绝道歉！易用性差也叫乱用，我也是真佩服你们这些社区维护的人，脚本不就是为了方便？以前的脚本能做到的方便到你们社区就退化了？ 还美其名曰 <我认为 v2ray 这样的项目确实也没有默认配置可言，请用户不要再将这件事作为 bug 提交上来，你们既然选择自建，就应该自己写自己的配置了。> 牛逼真的 你们真的是在写给自己玩的吧

**Comment by Copay** [comment]
没有能力就不要自建

**Comment by zenmaster-cd** [comment]
有能力没有能力？和易用是两个概念请你学好语文再来

**Comment by Copay** [comment]
> 有能力没有能力？和易用是两个概念请你学好语文再来

毕竟您的行为是很明显的无能狂怒嘛~

**Comment by zenmaster-cd** [comment]
你根本就看不到问题而转移话题，你认为无能狂怒就无能狂怒吧，毕竟你这种眼界看不到问题的根源，而是挑衅我的。

**Comment by EpLiar** [comment]
你一不付钱二不出力的，凭啥说三道四指手画脚的？
乞丐也要有个乞丐的样子

**Comment by studentmain** [comment]
值得一提的是，用户有选择第三方一键脚本的权利

**Comment by zenmaster-cd** [comment]
又来一个道德至高点的可以 真的是踩你们神经了 各种人生攻击就开始了

**Comment by studentmain** [comment]
至于你的问题，此脚本升级了什么：现在符合 Linux 关于文件系统中某些目录用途的的规范了

**Comment by zenmaster-cd** [comment]
对用户是有三方选择对权利，这是一个更易用的方案对于用户来说，为什么不用？难道你们就是为了让用户多花时间写更多的配置？

**Comment by EpLiar** [comment]
> 又来一个道德至高点的可以 真的是踩你们神经了 各种人生攻击就开始了

那我们凭什么为你这样的用户服务呢？你所提供的信息也毫无价值。

另外为什么脚本的配置文件要有信息？配置本身就可以多元化。文件为空都能拿来抱怨的，伸手党和无能无疑。

另外开源社区产品很多，不喜欢可以用别的，甚至你干脆就不使用 V2Ray，都没有问题。

**Comment by Copay** [comment]
目前的脚本和安装脚本的目的是相吻合的，事实上包管理器进行安装的v2ray-core也是同样的配置。
安装脚本!=一键脚本，这是常识。

**Comment by zenmaster-cd** [comment]
牛逼牛逼 拽的很哦 不说了 没必要说下去了

**Comment by studentmain** [comment]
> 难道你们就是为了让用户多花时间写更多的配置？

是的，毕竟 V2Ray 是平台，平台的所有功能都可以，而且应该试试。

**Comment by EpLiar** [comment]
> 对用户是有三方选择对权利，这是一个更易用的方案对于用户来说，为什么不用？难道你们就是为了让用户多花时间写更多的配置？

你找一个易用的方案比在这里让大家看笑话简单的多。

我们的社区太小，大家都很忙，容不下云产品经理、云程序员以及某些以无知为光荣的人。

**Comment by terminator850** [comment]
我咋没看明白呢…也没跟你收费啊，义务性的东西…觉得不好就找别的用呗…

**Comment by cpdyj** [comment]
见了鬼…

**Comment by IceCodeNew** [comment]
> > 难道你们就是为了让用户多花时间写更多的配置？
> 
> 是的，毕竟 V2Ray 是平台，平台的所有功能都可以，而且应该试试。

没错，这就是我说「我认为 v2ray 这样的项目确实也没有默认配置可言，请用户不要再将这件事作为 bug 提交上来，你们既然选择自建，就应该自己写自己的配置了」的意思。
选择自建的人要满足自己的使用需要，而每个人使用代理要解决的问题都不一样，过去做成类一键脚本那是过去，现在 v2ray 经过了几次大的变化以后还这样做就可能不合适了。
