### ISSUE TITLE
当系统未安装v2ray时，使用脚本安装老是报错，提示“Failed to stop v2ray.service: Unit v2ray.service not loaded. error: Stopping the V2Ray service failed.”

### ISSUE THREAD

**Issue by Yofo-me** [v2fly/fhs-install-v2ray#71]
> `如图，系统(Kubuntu 20.04 LTS)没有安装v2ray，使用脚本安装是报错，原因如图所示`

![image](https://user-images.githubusercontent.com/55388087/91541105-633ec380-e94e-11ea-9e99-bf05bdba0540.png)

**Comment by IceCodeNew** [comment]
> 贴错误日志的时候用 `` ``` `` 比截图更加友好。
> 

然后你看起来是在下载脚本到本地执行，而你下载 `install-release.sh` 脚本的时候看起来撞到墙了，所以你不妨先从这个地方着手解决一下。
目前看起来第一要排除你下载到本地的脚本是不是太旧了，因为最新的脚本已经不再通过从远程下载的方式配置本机的 service 文件了，而你既然在访问 `raw.githubusercontetn.com` 的时候撞墙，那执行旧脚本的时候就可能会遇到问题。
上面排除完再来考虑权限问题。 `DEBUG=1 bash install-release.sh` 试试
