### ISSUE TITLE
使用发行文件中的 systemd

### ISSUE THREAD

**Issue by kslr** [v2fly/fhs-install-v2ray#72]

**Comment by IceCodeNew** [comment]
我之前就考虑了一下这个问题，当时的思路是写一个 GitHub Action 去自动拉 v2ray-core 那个仓库里的文件内容。
后来一查 GitHub 不支持任何监视其他 repo 更新的动作，这个思路就只好作罢。
我打算蹲一个更好的思路，看有谁先提出来吧。

**Comment by kslr** [comment]
> 我之前就考虑了一下这个问题，当时的思路是写一个 GitHub Action 去自动拉 v2ray-core 那个仓库里的文件内容。
> 后来一查 GitHub 不支持任何监视其他 repo 更新的动作，这个思路就只好作罢。
> 我打算蹲一个更好的思路，看有谁先提出来吧。

只需要解压后从里面拷贝出来就好了

**Comment by IceCodeNew** [comment]
哦也行，

**Comment by kslr** [comment]
https://github.com/v2fly/fhs-install-v2ray/commit/4706d8e46c0d4e4ff7bd781a3b9d1fa104315367
