### ISSUE TITLE
error: Only Linux distributions using systemd are supported.

### ISSUE THREAD

**Issue by daiaji** [v2fly/fhs-install-v2ray#75]
好哥哥你摇了我吧，我只是想用alpine构建docker镜像。

**Comment by IceCodeNew** [comment]
这个问题已经有人问过了，你可以直接在那里跟（#54）
至于你说 docker 镜像的问题，v2ray 官方有提供 docker 镜像发布，在这里：https://hub.docker.com/r/v2fly/v2fly-core
如果你需要自定义，该 [仓库](https://github.com/v2fly/docker) 的 dockerfile 也可以供你参考和修改。所以我看不出你来这里寻求帮助的意义。

**Comment by daiaji** [comment]
@IceCodeNew 但是你要弄一个从Kubernetes变量里导出v2配置的，要改的东西又不止一点……
姑且只是搞个docker镜像，没必要从源码编译吧？
又不是发布预编译的二进制……
用下载脚本直接整不就完事了……

**Comment by IceCodeNew** [comment]
> 大家都在编译docker 镜像，凭什么你要从源码编译二进制，不低碳！不环保！

りしれ供三小。
特意编辑一遍最后给我看这个，是想承包我起床以后一整天的笑点吗？

**Comment by kslr** [comment]
想要就自己提交 pr 吧
