### ISSUE TITLE
服务方式无法启动，命令行却可以启动

### ISSUE THREAD

**Issue by klever1988** [v2fly/fhs-install-v2ray#76]
配置式https://github.com/v2fly/v2ray-examples/blob/master/VMess-TCP-TLS/config_server.json
系统centos8
ecc和rsa均有此症状
服务日志表示无法解析证书

**Comment by IceCodeNew** [comment]
无日志。
无常见问题排查过程的输出（参见 #63）

**Comment by klever1988** [comment]
[v2ray.log](https://github.com/v2fly/fhs-install-v2ray/files/5165152/v2ray.log)
