### ISSUE TITLE
 对于包括但不限于 v2ray 的证书读取问题的一点想法

### ISSUE THREAD

**Issue by unknowndev233** [v2fly/fhs-install-v2ray#80]
目前的 [方案](https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates) 的确是解决了证书的问题，不过看到隔壁 trojan-go https://github.com/p4gefau1t/trojan-go/issues/171 也有这种问题之后我有了一个想法

我对目前这个项目的解决方案的看法：
nobody 用作无特权的进程确实可行，但是读取证书的话有点不合适，因为有不少无特权进程都是 nobody 运行的

我在前一段时间看到了大概是 sdk24 以上的 Android 有一个组，叫 readproc
顾名思义，在这个组的进程可以读 /proc

那么有没有一种读取证书特权组呢？
当然，在今天没有

没有？要不做一个？
于是我就有了一个想法

做一个名为 readcert.conf 的文件并且应用它
`g readcert 89 "read cert"`
或者执行 `groupadd --system --gid 89` 创建这个组

然后更改想要读取证书的 service 文件
[Service] 下加 `Group=readcert`

记得设置好证书的权限
`chown root:readcert <证书公钥> <证书私钥> && chmod 640 <证书私钥>`

**Comment by kslr** [comment]
这不是设置权限的进阶吗

**Comment by unknowndev233** [comment]
> 这不是设置权限的进阶吗

是的，不过似乎没有人提出来过

**Comment by IceCodeNew** [comment]
其实我觉得最好的办法是用 HAProxy 做 TLS termination，何必在所有地方都做一遍证书设置呢？

**Comment by unknowndev233** [comment]
> 其实我觉得最好的办法是用 HAProxy 做 TLS termination，何必在所有地方都做一遍证书设置呢？

~~能在 HAProxy 分出 trojan 与 v2ray 的流量？~~ 如果有的人希望少装软件的话……

**Comment by IceCodeNew** [comment]
> > 其实我觉得最好的办法是用 HAProxy 做 TLS termination，何必在所有地方都做一遍证书设置呢？
> 
> ~能在 HAProxy 分出 trojan 与 v2ray 的流量？~ 如果有的人希望少装软件的话……

简单的思路当然是不同 path 做区分，你要是想玩更复杂的那就得自己琢磨了。毕竟要求这么高那就别指望配置简单了……
HAProxy 配置 TLS 和管理证书真的是即强大又简单
