### ISSUE TITLE
能支持Ubuntu 14.04的安装吗

### ISSUE THREAD

**Issue by qingfengshi** [v2fly/fhs-install-v2ray#86]
很久没有折腾服务器了，今天折腾一下，发现官方的go.sh脚本不能被弃用了，跳转到了这个项目。但是这个项目只能支持systemd的安装，我一直使用的Ubuntu 14的系统，突然就没有官方支持了。不知项目能够支持Ubuntu 14的安装吗？

**Comment by IceCodeNew** [comment]
https://github.com/v2fly/fhs-install-v2ray/issues/54#issuecomment-674654559

**Comment by qingfengshi** [comment]
请问一下，Ubuntu 16能够使用这个脚本吗？

**Comment by IceCodeNew** [comment]
Search, before you ask.
https://wiki.ubuntu.com/SystemdForUpstartUsers

> that systemd is only fully supported in Ubuntu 15.04 and later releases.

BTW 建议你尽量选择更新的 LTS 版本，免得再遇到其他问题。
我不敢代表本项目的其他维护者，但是我本人并没有充裕的时间和兴趣为过于老旧的操作系统提供支持。

**Comment by qingfengshi** [comment]
好的，谢谢。
刚才尝试了16.04安装v2ray，至少到v4.21.3是不支持的，原因是”This version does not support
verification“。说明这个脚本也无法支持旧版本的安装。
对旧版本放弃维护可以理解，可是不需要让旧版本无法使用。我这样只需要TLS+websocket的人，新版本加入的东西对我没有太大的意义。
个人认为完全可以保留go.sh的脚本，然后v2fly官网注明这个脚本支持到哪个版本，新脚本从哪个版本开始支持。

**Comment by IceCodeNew** [comment]
> 好的，谢谢。 刚才尝试了16.04安装v2ray，至少到v4.21.3是不支持的，原因是”This version does not support verification“。说明这个脚本也无法支持旧版本的安装。 对旧版本放弃维护可以理解，可是不需要让旧版本无法使用。我这样只需要TLS+websocket的人，新版本加入的东西对我没有太大的意义。 个人认为完全可以保留go.sh的脚本，然后v2fly官网注明这个脚本支持到哪个版本，新脚本从哪个版本开始支持。

这种日常被拿出来讨论的问题你能不能先搜索一遍再来重复……
https://github.com/v2fly/fhs-install-v2ray/issues/51#issuecomment-674528490

**Comment by IceCodeNew** [comment]
然后如果你理解 git，那你想要把旧的 go.sh 脚本重新翻出来用实在是很简单的一件事。
我这边花了不到 30 秒就把相关的更改找出来，你只要复制这个 commit 之前的文件内容就可以自己拿到本地安装使用了。

https://github.com/v2ray/v2ray-core/commit/ac8bc4e7316d30925b91282ac49951446b1dedfe

老兄，不要自己都还没动手就开始求人了，这样很逊欸。
