### ISSUE TITLE
你们这里安装的v2ray不要求服务器是北京时间了？

### ISSUE THREAD

**Issue by byronsong** [v2fly/fhs-install-v2ray#87]
你们这里安装的v2ray不要求服务器是北京时间了？
系统：Amazon linux 2 AMI

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
[ec2-user@ip-10-0-0-242 ~]$ cat /etc/sysconfig/clock
ZONE="UTC"
UTC=true
[ec2-user@ip-10-0-0-242 ~]$ date -R
Tue, 08 Sep 2020 08:57:05 +0000
[ec2-user@ip-10-0-0-242 ~]$ v2ray --version
V2Ray 4.27.5 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.7 linux/amd64)
A unified platform for anti-censorship.
[ec2-user@ip-10-0-0-242 ~]$

**Comment by IceCodeNew** [comment]
v2ray 对系统时区设置一直没有要求
> VMess 依赖于系统时间，请确保使用 V2Ray 的系统 UTC 时间误差在 90 秒之内，时区无关

https://www.v2fly.org/config/protocols/vmess.html#outboundconfigurationobject
