### ISSUE TITLE
[重要提示] 安装脚本对多配置文件的启动方式支持不完善。

### ISSUE THREAD

**Issue by IceCodeNew** [v2fly/fhs-install-v2ray#89]
关于使用多配置文件方式启动 v2ray 的用户，在 #81 以后使用脚本升级几乎一定会遇到问题。
这个问题其实是由 #60 引入的，在 https://github.com/v2fly/fhs-install-v2ray/issues/88#issuecomment-689715343 这里我对导致这一问题的更改做了详细的解释。

在我撰写这条 Issue 的时候，其实本项目的安装脚本在系统里安装的两份 service unit files（分别是 `v2ray.service` 和 `v2ray@.service`）都是不适合多配置文件启动方式的。
因此在目前而言还需要使用多配置文件的用户手动做下面的更改（请根据自己需要自行调整配置文件目录）：
```bash
mkdir -p '/etc/systemd/system/v2ray.service.d'
echo 'ExecStart=
ExecStart=/usr/local/bin/v2ray -confdir /usr/local/etc/v2ray/conf.d/' \
> '/etc/systemd/system/v2ray.service.d/v2ray_execstart_multiconf.conf'
systemctl daemon-reload && systemctl restart v2ray
```

关于这些不便还请谅解，欢迎提交 PR 来完善脚本对多配置文件启动方式的支持。
其他在使用多配置文件方式启动过程中的问题，也欢迎 **另外开 issue 提出**。

**Comment by kslr** [comment]
这个问题应该全面解决

**Comment by IceCodeNew** [comment]
> 这个问题应该全面解决

其实要解决也容易，把我上面的解决办法写进安装脚本就行了。
问题就在于我拿不准到底该以什么为多配置文件的默认保存位置，我真的不觉得跑去和单配置文件挤一个目录是个好想法（`/usr/local/etc/v2ray`）

**Comment by kslr** [comment]
conf.d 是一种 include 的思想，和设计不符合，应该进行更多讨论

**Comment by IceCodeNew** [comment]
> conf.d 是一种 include 的思想，和设计不符合，应该进行更多讨论

是啊，确实应该有更好的起名

**Comment by IceCodeNew** [comment]
Closed by #114.
