### ISSUE TITLE
升级的时候能否不覆盖 systemd config

### ISSUE THREAD

**Issue by alexyangjie** [v2fly/fhs-install-v2ray#91]
如题。新的安装脚本默认用nobody运行v2ray，会导致许多问题（不仅是证书权限问题），例如DS file和其他软件的集成，不能仅用nobody运行。我在本机将/etc/systemd/system/v2ray.service更改为用root运行，解决了问题。但再次运行该脚本升级的时候，又把默认的systemd文件覆盖进来，导致v2ray出错。

希望在升级程序时，不要覆盖本地的systemd config。

**Comment by IceCodeNew** [comment]
#90
