### ISSUE TITLE
centos7 从4.27.0更新到4.28.0无法启动

### ISSUE THREAD

**Issue by usgate** [v2fly/fhs-install-v2ray#95]
按https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this 更新
命令 id nobody
提示 uid=99(nobody) gid=99(nobody) groups=99(nobody)

命令 chown -R nobody:nogroup /srv/http/
提示 chown: invalid group: ‘nobody:nogroup’

--test测试正常，但是无法启动服务，通过命令行 /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json 可以正常启动

**Comment by kslr** [comment]
https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs
