### ISSUE TITLE
centos7 从4.27.0更新到4.28.0无法启动

### ISSUE THREAD

**Issue by usgate** [v2fly/fhs-install-v2ray#96]
按https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this 更新
命令 id nobody
提示 uid=99(nobody) gid=99(nobody) groups=99(nobody)

命令 chown -R nobody:nogroup /srv/http/
提示 chown: invalid group: ‘nobody:nogroup’

--test测试正常，但是无法启动服务，通过命令行 /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json 可以正常启动
service v2ray start启动失败
附上journalctl 日志

V2Ray 4.28.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
v2ray[4946]: A unified platform for anti-censorship.
v2ray[4946]: main: failed to read config files: [/usr/local/etc/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl:
v2ray[4946]: v2ctl> Read config:  /usr/local/etc/v2ray/config.json
v2ray[4946]: v2ray.com/core/infra/conf: Failed to build TLS config. > v2ray.com/core/infra/conf: failed to parse certificate > open /opt/caddyserver/.caddy/acme/acme-v02.api.letsencrypt.org/sites/xxx.xxx.com/xxx.xxx.com.crt: permission denied > exit status 255
systemd[1]: v2ray.service: main process exited, code=exited, status=23/n/a
systemd[1]: Unit v2ray.service entered failed state.
systemd[1]: v2ray.service failed.
systemd[1]: v2ray.service holdoff time over, scheduling restart.
systemd[1]: Stopped V2Ray Service.
systemd[1]: start request repeated too quickly for v2ray.service
systemd[1]: Failed to start V2Ray Service.
systemd[1]: Unit v2ray.service entered failed state.
systemd[1]: v2ray.service failed.

**Comment by DuckSoft** [comment]
https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates

**Comment by IceCodeNew** [comment]
groups=99(nobody)

还没看明白吗？nobody 用户属于 nobody 组，而不属于 nogroup 组，你连迁移的步骤都没完成后面自然会遇到问题。

Issue 连着被关了两个还在锲而不舍继续 SPAM，你要知道发 Issue 是来求助而不是来讨嫌的。有人关了你的 Issue 说明你的问题答案几乎就在你面前，或者你做的事让人不想给你解答。

希望你学会如何分析问题和独立地解决问题，只有确实一个人存在困难时才 **合理地** 利用求助。
